import json
qs = []
def add(q, opts, ans, exp, topic, level="NEET", typ="Single Correct MCQ"):
    qs.append(dict(q=q,opts=opts,ans=ans,exp=exp,topic=topic,level=level,type=typ))
base = [
("The three critical research areas of biotechnology described in NCERT include providing the best catalyst, creating optimal conditions and:",["Developing only chemical fertilisers","Downstream processing technologies to purify the product","Replacing all microbes with plants","Avoiding genetic engineering"],"B","A complete biotechnology process also requires recovery and purification of the product.","Biotechnological applications overview"),
("A genetically modified organism is one whose:",["Phenotype changes only because of nutrition","Genetic material has been altered using genetic engineering","Chromosome number changes naturally in meiosis","Cells are grown only in tissue culture"],"B","GM organisms contain deliberately altered genetic material.","Genetically modified organisms"),
("Which is a stated advantage of genetically modified crops?",["Increased reliance on chemical pesticides","Reduced post-harvest losses","Guaranteed elimination of all pests","Complete removal of environmental effects"],"B","NCERT lists reduced post-harvest losses among the benefits of GM crops.","Advantages of GM crops"),
("GM crops can improve food quality by:",["Reducing all proteins","Enhancing nutritional value","Eliminating carbohydrates","Preventing seed formation"],"B","Biofortification through genetic engineering can improve nutritional quality.","Advantages of GM crops"),
("A major ecological objective of pest-resistant GM crops is to:",["Increase pesticide use","Reduce dependence on chemical pesticides","Remove all insects from ecosystems","Prevent pollination"],"B","In-built resistance can reduce pesticide application.","Pest-resistant crops"),
("Tolerance to abiotic stresses in GM plants may include tolerance to:",["Drought, salinity and cold","Only pathogens","Only herbivores","Only high oxygen"],"A","Abiotic stresses include drought, salinity, heat and cold.","Abiotic-stress tolerance"),
("The use of genetically modified plants to reduce post-harvest losses primarily improves:",["Food availability","Mutation rate","Chromosome pairing","Mendelian segregation"],"A","Reduced spoilage allows a larger fraction of production to reach consumers.","Advantages of GM crops"),
("A crop engineered to use minerals more efficiently could help prevent:",["Exhaustion of soil fertility","DNA replication","Seed germination","Transcription"],"A","NCERT notes improved mineral-use efficiency as a possible GM benefit.","Mineral-use efficiency"),
("Which statement is most accurate regarding GM plants?",["Every GM crop has the same inserted gene","Different GM crops are designed for different useful traits","GM crops cannot reproduce","GM crops are always pesticide-producing"],"B","The engineered trait depends on the gene and intended application.","GM crops"),
("The bacterium that provides many Bt toxin genes is:",["Rhizobium leguminosarum","Bacillus thuringiensis","Agrobacterium tumefaciens","Escherichia coli"],"B","B. thuringiensis produces insecticidal crystal proteins.","Bt crops"),
("Bt in Bt cotton stands for:",["Biological transfer","Bacillus thuringiensis","Bacterial transcription","Beta toxin"],"B","The name refers to the source bacterium of cry genes.","Bt crops"),
("The insecticidal protein of Bacillus thuringiensis is produced in the bacterium as:",["An active soluble enzyme","An inactive protoxin","A lipid","An antibody"],"B","The crystal protein is synthesised as an inactive protoxin.","Bt toxin mechanism"),
("Bt protoxin becomes active in the insect gut because of:",["Acidic pH","Alkaline pH","Low temperature","Absence of proteases"],"B","The alkaline gut environment solubilises and activates the protoxin.","Bt toxin mechanism"),
("After activation, Bt toxin primarily acts by:",["Blocking DNA replication in plant cells","Binding to midgut epithelial cells and forming pores","Preventing insect egg formation directly","Destroying the insect exoskeleton"],"B","Pore formation causes cell swelling, lysis and insect death.","Bt toxin mechanism"),
("Bt toxin kills susceptible insects mainly due to damage to the:",["Nervous system","Midgut epithelium","Malpighian tubules only","Reproductive organs"],"B","Activated toxin damages cells lining the insect midgut.","Bt toxin mechanism"),
("The cry genes encode:",["Antibiotic resistance proteins","Insecticidal crystal proteins","Human insulin","Interferons"],"B","Cry genes code for Bt crystal proteins.","Cry genes"),
("Different cry genes are useful because they:",["All kill exactly the same insect","May be toxic to different groups of insects","Prevent gene expression in plants","Encode identical proteins"],"B","Different Cry proteins have different insect specificities.","Cry genes"),
("The genes cryIAc and cryIIAb have been used to control:",["Corn borer only","Cotton bollworms","Nematodes only","Mosquitoes only"],"B","NCERT links these cry genes with cotton bollworm control.","Bt cotton"),
("The gene cryIAb is commonly associated with resistance to:",["Corn borer","Cotton bollworm only","Root-knot nematode","Aphid"],"A","CryIAb is effective against corn borer.","Cry gene specificity"),
("A Bt crop does not normally harm its own cells because the toxin is:",["Never produced in the plant","Specific to susceptible insect gut receptors and conditions","Destroyed by plant DNA","Active only in acidic plant vacuoles"],"B","Toxicity depends on activation and receptor binding in susceptible insects.","Bt crop selectivity"),
]
for x in base: add(*x)

# 21-40 Bt and RNAi
more = [
("An insect feeding on Bt cotton dies after the toxin:",["Enters its alkaline gut and is activated","Is converted into DNA","Prevents photosynthesis in the insect","Binds to haemoglobin"],"A","Gut alkalinity activates the protoxin, which then damages epithelial cells.","Bt toxin mechanism"),
("Which sequence correctly represents Bt toxin action?",["Pore formation → ingestion → activation → receptor binding","Ingestion → activation → receptor binding → pore formation","Activation in plant → ingestion → DNA cleavage","Receptor binding → gene insertion → pore formation"],"B","The insect ingests protoxin, which is activated, binds receptors and forms pores.","Bt toxin mechanism"),
("The Bt toxin crystals are harmless to Bacillus thuringiensis because they are:",["Secreted immediately","Present as inactive protoxins","Made only after bacterial death","Neutralised by antibiotics"],"B","The bacterium stores the protein in an inactive crystalline form.","Bt toxin mechanism"),
("A crop carrying a cry gene is best described as:",["A transgenic crop with insect resistance","A hybrid produced only by crossing","A polyploid crop","A crop resistant to every pathogen"],"A","Insertion and expression of a cry gene create transgenic insect resistance.","Bt crops"),
("A major benefit of Bt cotton is reduction in the use of:",["Irrigation water in every condition","Insecticides against target bollworms","Nitrogen fertilisers only","Herbicides against weeds"],"B","Bt cotton reduces insecticide use for susceptible target pests.","Bt cotton"),
("Resistance management in Bt crops is important because:",["Target insects can evolve resistant alleles","Bt genes always disappear in one generation","Plants cannot express proteins continuously","All insects are naturally immune"],"A","Strong selection can increase resistance alleles in pest populations.","Bt resistance - application","JEE Main"),
("Planting non-Bt refuge plants near Bt crops can help by:",["Increasing only resistant insects","Maintaining susceptible insects that mate with resistant survivors","Stopping gene expression in Bt plants","Destroying all pest populations"],"B","Refuges slow resistance evolution by preserving susceptible alleles.","Bt resistance - application","JEE Main"),
("RNA interference is a method of:",["Increasing translation of every mRNA","Silencing a specific gene using complementary RNA","Duplicating chromosomes","Producing antibodies"],"B","RNAi reduces expression of a target gene through sequence-specific RNA.","RNA interference"),
("RNA interference operates in all eukaryotic organisms primarily as a mechanism of:",["Cell wall synthesis","Cellular defence","DNA packaging","Protein secretion"],"B","NCERT describes RNAi as a cellular defence mechanism.","RNA interference"),
("RNAi can be triggered by:",["Single-stranded lipid","Double-stranded RNA","Only ribosomal RNA","DNA without transcription"],"B","Double-stranded RNA initiates sequence-specific silencing.","RNA interference"),
("In RNAi, the silencing RNA is complementary to:",["Every cellular protein","The target mRNA","The target lipid","The ribosomal DNA only"],"B","Complementary interaction prevents expression of the target mRNA.","RNA interference"),
("The nematode controlled through RNAi in transgenic tobacco is:",["Ascaris lumbricoides","Meloidogyne incognita","Wuchereria bancrofti","Taenia solium"],"B","M. incognita infects tobacco roots and was targeted by RNAi.","RNAi and nematode resistance"),
("Meloidogyne incognita causes damage primarily by infecting:",["Flowers","Roots","Pollen grains","Fruit surface only"],"B","It is a root-knot nematode.","RNAi and nematode resistance"),
("The vector used to introduce nematode-specific genes into tobacco was based on:",["Bacteriophage lambda only","Agrobacterium","Retrovirus","Plasmodium"],"B","Agrobacterium vectors delivered sequences producing complementary RNAs.","RNAi and nematode resistance"),
("The transgenic tobacco plant produced both sense and antisense RNA. These RNAs:",["Formed double-stranded RNA","Produced two unrelated proteins","Destroyed plant chromosomes","Activated nematode genes"],"A","Complementary sense and antisense transcripts hybridised to form dsRNA.","RNAi and nematode resistance"),
("Double-stranded RNA in the transgenic plant caused:",["Silencing of a specific nematode mRNA","Activation of all nematode genes","Conversion of RNA to protein without ribosomes","Increased nematode reproduction"],"A","The dsRNA triggered RNAi against the complementary nematode transcript.","RNAi and nematode resistance"),
("The nematode could not survive in the transgenic host because:",["Its essential gene expression was silenced","The plant had no roots","The nematode became diploid","Bt toxin always kills nematodes"],"A","RNAi blocked an essential target transcript in the parasite.","RNAi and nematode resistance"),
("Which pair is correctly matched?",["Bt cotton - RNAi against Meloidogyne","Transgenic tobacco - RNAi against Meloidogyne","Golden rice - Bt toxin against bollworm","Humulin - pest resistance"],"B","The NCERT RNAi example uses transgenic tobacco against M. incognita.","RNAi application"),
("RNAi is highly specific because it depends on:",["Similarity in organism size","Complementary nucleotide sequences","Identical chromosome number","Common cell shape"],"B","Base pairing allows selective recognition of target RNA.","RNA interference"),
("A gene-silencing construct containing inverted complementary sequences is designed mainly to produce:",["Double-stranded RNA","A steroid","A polysaccharide","A chromosome deletion"],"A","Complementary transcripts can fold or hybridise into dsRNA.","RNAi technology","JEE Main"),
]
for x in more: add(*x)

# 41-60 medicine and insulin
med = [
("Recombinant therapeutics are preferred over similar products isolated from non-human sources because they:",["Always cost nothing","May reduce unwanted immunological reactions","Cannot be purified","Contain no amino acids"],"B","Human-compatible recombinant proteins can be safer and more consistent.","Recombinant therapeutics"),
("The first genetically engineered human insulin was prepared commercially by:",["Eli Lilly","Genentech only","WHO","GEAC"],"A","Eli Lilly produced recombinant human insulin in 1983.","Recombinant insulin"),
("Human insulin consists of:",["One polypeptide chain","Two polypeptide chains, A and B","Three identical chains","A DNA and an RNA chain"],"B","Mature insulin contains A and B polypeptide chains linked by disulfide bonds.","Structure of insulin"),
("The A and B chains of insulin are linked by:",["Peptide bonds only between chains","Disulfide bonds","Hydrogen bonds only","Phosphodiester bonds"],"B","Disulfide bridges stabilise mature insulin.","Structure of insulin"),
("In mammals, insulin is initially synthesised as:",["Active insulin without extra sequence","Proinsulin containing an additional C peptide","A carbohydrate","Two separate mature chains in different cells"],"B","Proinsulin includes the connecting C peptide.","Proinsulin"),
("The C peptide is absent from:",["Proinsulin","Mature insulin","The insulin gene","Pancreatic cells"],"B","C peptide is removed during maturation of proinsulin.","Proinsulin"),
("The main challenge in producing human insulin in bacteria was that bacteria:",["Cannot synthesise any protein","Do not naturally process proinsulin exactly as human cells do","Have no DNA","Destroy all disulfide bonds"],"B","The bacterial system does not perform normal human proinsulin processing.","Recombinant insulin"),
("Eli Lilly produced human insulin by synthesising DNA sequences for:",["Only the C peptide","A and B chains separately","The whole pancreas","Only insulin receptors"],"B","A- and B-chain coding sequences were expressed separately in E. coli.","Recombinant insulin"),
("After separate production in bacteria, insulin A and B chains were:",["Joined by disulfide bonds","Joined by phosphodiester bonds","Converted into DNA","Mixed without purification"],"A","The purified chains were combined to form functional insulin.","Recombinant insulin"),
("Recombinant human insulin is also called:",["Humulin","Penicillin","Interferon","Cry protein"],"A","Humulin is recombinant human insulin.","Recombinant insulin"),
("Earlier insulin preparations obtained from cattle and pigs sometimes caused:",["Mutation in every patient","Allergic or immunological reactions","Immediate gene therapy","Nematode infection"],"B","Differences in animal insulin could trigger immune responses.","Insulin therapy"),
("Which component is removed while converting proinsulin to mature insulin?",["A chain","B chain","C peptide","All disulfide bonds"],"C","The connecting peptide is cleaved during maturation.","Proinsulin"),
("If a recombinant bacterial product contains insulin A, B and C regions in one chain, the immediate product most closely resembles:",["Mature insulin","Proinsulin","Glucagon","Antibody"],"B","Presence of C peptide indicates proinsulin-like structure.","Proinsulin - application"),
("A person lacking functional insulin can be treated by recombinant DNA technology through production of:",["A human peptide hormone","A restriction enzyme","A Bt protoxin","An RNAi construct"],"A","Recombinant insulin is a therapeutic peptide hormone.","Recombinant therapeutics"),
("Gene therapy aims to:",["Replace every cell of the body","Correct or compensate for a defective gene","Increase pesticide use","Remove all introns from nature"],"B","A normal functional gene is introduced to restore missing activity.","Gene therapy"),
("The first clinical gene therapy mentioned in NCERT was given in 1990 to a child with:",["Haemophilia","ADA deficiency","Down syndrome","Diabetes mellitus"],"B","The first gene therapy case involved adenosine deaminase deficiency.","ADA gene therapy"),
("ADA deficiency affects the:",["Immune system","Digestive system only","Skeletal system only","Blood group system"],"A","ADA deficiency causes severe immune dysfunction.","ADA deficiency"),
("ADA deficiency may be treated by:",["Bone marrow transplantation, enzyme replacement or gene therapy","Only antibiotics","Only Bt toxin","Only RNAi in plants"],"A","NCERT describes all three approaches.","ADA deficiency"),
("In ex vivo ADA gene therapy, lymphocytes are:",["Removed, genetically corrected and returned to the patient","Destroyed permanently","Converted into bacteria","Injected with Bt crystals"],"A","Patient lymphocytes are cultured, modified and reinfused.","ADA gene therapy"),
("A functional ADA cDNA is introduced into lymphocytes using:",["A retroviral vector","A pollen tube","A plasmid-free mineral","A ribosome"],"A","Retroviral vectors can deliver the functional gene to cultured cells.","ADA gene therapy"),
]
for x in med: add(*x)

# 61-80 gene therapy and molecular diagnosis
diag = [
("Gene therapy using genetically modified lymphocytes may need repeated treatment because:",["Lymphocytes are not immortal","ADA cDNA mutates instantly","All vectors are destroyed before entry","The patient has no blood"],"A","Corrected lymphocytes have a limited lifespan.","ADA gene therapy"),
("A potentially permanent cure for ADA deficiency would require introduction of the functional gene into:",["Short-lived mature erythrocytes","Cells at an early embryonic stage or suitable stem cells","Only gut bacteria","Bt cotton"],"B","Long-lived progenitor cells can pass the correction to descendant cells.","ADA gene therapy"),
("Enzyme replacement therapy for ADA deficiency involves giving the patient:",["Functional ADA enzyme periodically","A cry gene","Only insulin","Double-stranded nematode RNA"],"A","The missing enzyme can be supplied, but repeated administration is needed.","ADA deficiency"),
("Which treatment modifies a patient's own cells outside the body?",["Ex vivo gene therapy","Bt cotton cultivation","ELISA only","Biopiracy"],"A","Cells are removed, engineered and returned.","Gene therapy"),
("A normal gene introduced into a patient is intended primarily to:",["Compensate for a non-functional gene","Change the patient's blood group","Cause aneuploidy","Produce a pesticide"],"A","The therapeutic gene restores a missing or defective function.","Gene therapy"),
("Molecular diagnosis is especially useful because it can detect disease:",["Only after severe symptoms appear","At an early stage, sometimes before symptoms","Only after death","Without any biological sample"],"B","PCR and related methods detect low amounts of pathogen or abnormal genes.","Molecular diagnosis"),
("Conventional diagnostic methods may fail early in infection because:",["Pathogen concentration may be too low","DNA cannot exist in pathogens","Antibodies are always absent forever","All cells are identical"],"A","Molecular amplification can reveal very small amounts of nucleic acid.","Molecular diagnosis"),
("PCR assists diagnosis by:",["Amplifying a specific nucleic acid sequence","Directly producing antibodies","Counting chromosomes under a microscope only","Destroying all proteins"],"A","PCR makes many copies of a target DNA sequence.","PCR diagnosis"),
("PCR can help detect HIV by amplifying:",["Viral nucleic acid sequences","Human insulin","Bt toxin crystals","Only antibodies"],"A","Specific viral sequences can be detected even at low abundance.","PCR diagnosis"),
("PCR is useful in cancer diagnosis because it can detect:",["Mutations in relevant genes","Only blood pressure","Every cancer without a sample","Only bacterial toxins"],"A","Specific genetic alterations can be amplified and identified.","PCR diagnosis"),
("A radioactive single-stranded DNA or RNA molecule used to identify a complementary sequence is called a:",["Probe","Primer-free enzyme","Vector host","Protoxin"],"A","A labelled probe hybridises with its complementary target.","Nucleic acid probes"),
("A probe detects a target sequence through:",["Complementary base pairing","Peptide bonding","Disulfide bonding","Chromosome nondisjunction"],"A","Hybridisation depends on sequence complementarity.","Nucleic acid probes"),
("In autoradiography, a clone carrying a mutated gene may fail to appear if:",["The labelled probe does not hybridise to the altered sequence","The DNA is double-stranded","The sample contains protein","The film contains silver"],"A","A sequence change can prevent complementary probe binding.","Probe-based diagnosis"),
("ELISA is based on the principle of:",["Antigen-antibody interaction","DNA-DNA replication","RNA interference","Chromosome segregation"],"A","ELISA detects antigens or antibodies using specific immune binding.","ELISA"),
("ELISA may detect infection by identifying:",["Pathogen antigens or host antibodies","Only chromosome number","Only lipids","Only mRNA codons"],"A","Both antigen detection and antibody detection formats are possible.","ELISA"),
("Which method is most directly suited for amplifying a minute amount of pathogen DNA?",["PCR","ELISA","Pedigree analysis","Gel staining alone"],"A","PCR exponentially amplifies target DNA.","Molecular diagnosis"),
("Which method directly depends on antigen-antibody specificity?",["PCR","ELISA","DNA fingerprinting","RNAi"],"B","ELISA is an immunological assay.","ELISA"),
("A patient has too little viral DNA for direct visual detection. The best first step is:",["PCR amplification","Bt toxin treatment","Insulin production","Plant transformation"],"A","PCR raises the target DNA concentration to detectable levels.","PCR diagnosis"),
("A labelled probe will bind most strongly to:",["A complementary nucleic acid sequence","Any protein with the same mass","A non-complementary lipid","An unrelated chromosome region"],"A","Stable hybridisation requires complementary bases.","Nucleic acid probes"),
("Molecular diagnosis can identify a genetic disorder by detecting:",["A mutated gene sequence","Only environmental temperature","Only the patient's age","A pest-resistant crop"],"A","Sequence-specific methods can reveal disease-causing mutations.","Molecular diagnosis"),
]
for x in diag: add(*x)

# 81-100 transgenic animals
animals = [
("Animals whose genome has been deliberately modified to carry a foreign gene are called:",["Transgenic animals","Clones only","Hybrids only","Polyploids only"],"A","A transgene is introduced and maintained in the animal genome.","Transgenic animals"),
("The majority of existing transgenic animals are:",["Cows","Mice","Fish","Goats"],"B","NCERT states that over 95% of transgenic animals are mice.","Transgenic animals"),
("Transgenic animals are used to study:",["Normal physiology and development","Only crop yield","Only soil fertility","Only bacterial conjugation"],"A","Gene regulation and developmental roles can be analysed in whole animals.","Uses of transgenic animals"),
("A transgenic animal carrying an altered gene can help determine:",["How that gene contributes to normal biological function","Only its blood group","The pH of soil","The age of a fossil"],"A","Changing gene activity reveals its physiological role.","Normal physiology and development"),
("Transgenic disease models are created mainly to:",["Understand disease mechanisms and test treatments","Increase pesticide resistance in cotton","Produce hybrid seeds","Study Mendel's peas only"],"A","Engineered animals can mimic human diseases.","Disease models"),
("Examples of diseases studied using transgenic animal models include:",["Cancer, cystic fibrosis and rheumatoid arthritis","Only malaria","Only cholera","Only colour blindness"],"A","NCERT lists several human disorders modelled in animals.","Disease models"),
("A transgenic cow named Rosie produced milk enriched with:",["Human alpha-lactalbumin","Bt toxin","Human insulin only","ADA enzyme only"],"A","Rosie's milk contained human alpha-lactalbumin.","Biological products"),
("Rosie produced human protein-enriched milk in:",["1997","1983","1990","2005"],"A","NCERT records Rosie as the first transgenic cow producing such milk in 1997.","Rosie"),
("The milk produced by Rosie was nutritionally more balanced for human babies because it contained:",["Human alpha-lactalbumin","CryIAb","C peptide","Phenylalanine hydroxylase"],"A","The introduced human milk protein improved nutritional suitability.","Rosie"),
("Transgenic animals can produce biological products by:",["Expressing useful human proteins in milk or other tissues","Deleting all genes","Preventing transcription","Eliminating ribosomes"],"A","Animals can function as bioreactors for therapeutic proteins.","Biological products"),
("Before a vaccine is used in humans, its safety may be tested in:",["Transgenic animals","Only bacteria","Only plants","Only test tubes without cells"],"A","Transgenic models can support vaccine safety assessment.","Vaccine safety"),
("Transgenic mice have been used to test the safety of:",["Polio vaccine","Only insulin","Bt cotton","Golden rice"],"A","NCERT cites polio vaccine safety testing in transgenic mice.","Vaccine safety"),
("Chemical safety testing on transgenic animals is also called:",["Toxicity or safety testing","Gene silencing","Biopiracy","Hybridisation"],"A","Animals can be engineered to respond sensitively to toxic substances.","Chemical safety testing"),
("Transgenic animals made more sensitive to toxic substances allow researchers to:",["Obtain toxicity results in less time","Eliminate all controls","Avoid measuring any response","Produce pesticides"],"A","Enhanced sensitivity can reveal toxic effects rapidly.","Chemical safety testing"),
("Which is not a major use of transgenic animals listed in NCERT?",["Study of normal physiology","Disease models","Vaccine safety","Routine production of chemical fertilisers"],"D","Chemical fertiliser manufacture is not one of the listed uses.","Uses of transgenic animals"),
("A transgenic model of a human disease is valuable when it:",["Reproduces relevant features of the disease","Has no altered genes","Cannot be studied","Produces only normal offspring"],"A","Similarity to human pathology enables mechanistic and therapeutic research.","Disease models"),
("The term 'biological products' in transgenic-animal applications refers mainly to:",["Useful proteins or therapeutics produced by living systems","Only body mass","Only animal feed","Chromosome stains"],"A","Engineered animals can synthesise valuable biomolecules.","Biological products"),
("A scientist introduces a human protein gene into a goat so that the protein is secreted in milk. This is an example of:",["Production of a biological product","RNAi against a nematode","Molecular diagnosis","Biopiracy"],"A","The animal is used as a living production system.","Transgenic animals - application"),
("An animal engineered to carry an oncogene is most directly useful as a:",["Cancer model","Bt crop","DNA probe","Biofertiliser"],"A","Such animals can model tumour development.","Disease models"),
("Which comparison is correct?",["PCR amplifies DNA; transgenic animals model gene function in whole organisms","ELISA amplifies DNA; PCR produces milk proteins","RNAi creates antibodies; probes produce insulin","Bt toxin diagnoses cancer"],"A","The paired functions are accurate.","Biotechnology applications integration"),
]
for x in animals: add(*x)

# 101-115 ethics, GEAC, patents, biopiracy
ethics = [
("The organisation mentioned in NCERT that evaluates the validity of GM research and safety of introducing GM organisms for public use is:",["GEAC","WHO only","ICAR examination board","UNESCO"],"A","GEAC evaluates biosafety and proposed release of GM organisms.","GEAC"),
("GEAC is concerned particularly with:",["Biosafety of genetically modified organisms","Mendelian ratios only","Insulin dosage","Fossil dating"],"A","Its role includes evaluation of GM research and environmental/public safety.","GEAC"),
("Ethical standards are required in biotechnology because genetic modification may affect:",["Humans, other organisms and the environment","Only laboratory glassware","Only textbook printing","Only pH paper"],"A","Biotechnology can have broad biological and social consequences.","Ethical issues"),
("A patent grants the inventor:",["Legal rights over an invention for a limited period","Permanent ownership of all natural organisms","Automatic approval for environmental release","Freedom from safety testing"],"A","Patents provide time-limited legal protection for qualifying inventions.","Biopatents"),
("A biopatent is a patent related to:",["Biological entities, products or processes","Only mechanical engines","Only literary works","Only mineral ores"],"A","Biopatents concern biological materials and biotechnology inventions.","Biopatents"),
("Biopiracy refers to:",["Unauthorised use of bioresources and traditional knowledge without fair compensation","Legal cultivation of Bt cotton","PCR diagnosis","Production of insulin"],"A","It involves exploitation without proper permission or benefit sharing.","Biopiracy"),
("Developing nations are often rich in:",["Biodiversity and traditional knowledge","Only patented drugs","Only transgenic mice","Only laboratory equipment"],"A","Their biological resources and indigenous knowledge may attract commercial interest.","Biopiracy"),
("A foreign company patents a product developed from an indigenous medicinal practice without acknowledging or compensating the community. This is:",["Biopiracy","Gene therapy","Molecular diagnosis","RNA interference"],"A","Traditional knowledge has been commercially appropriated without fair benefit sharing.","Biopiracy"),
("The turmeric patent controversy is associated with claims involving:",["Wound-healing properties","Bt toxin","Human insulin","ADA deficiency"],"A","Traditional Indian knowledge of turmeric's wound-healing use was central to the dispute.","Biopiracy examples"),
("The basmati controversy involved intellectual property claims related to:",["Rice varieties and grain traits","Human genes","Bt cotton toxin only","Polio vaccine"],"A","Basmati germplasm and characteristic traits raised biopiracy concerns.","Biopiracy examples"),
("The neem controversy is commonly linked with patents concerning:",["Pesticidal or antifungal uses derived from neem","Human insulin","ADA gene therapy","Transgenic mice"],"A","Traditional uses of neem prompted challenges to certain foreign patent claims.","Biopiracy examples"),
("Fair benefit sharing means that:",["Communities providing resources or knowledge receive appropriate recognition and returns","Only companies receive profits","No safety testing occurs","All patents last forever"],"A","Equitable sharing addresses ethical use of biological resources.","Benefit sharing"),
("Approval of a GM crop should consider:",["Food safety, environmental effects and gene flow","Only seed colour","Only company profit","Only plant height"],"A","Risk assessment must consider health and ecological consequences.","Biosafety"),
("Uncontrolled transfer of a transgene to wild relatives is a concern because it may:",["Alter ecological interactions","Always improve biodiversity","Prevent all reproduction","Have no possible effect"],"A","Gene flow can affect wild populations and ecosystems.","Biosafety"),
("The need for regulation of biotechnology arises because:",["Powerful applications may carry health, environmental and ethical risks","Recombinant DNA never works","All GM organisms are identical","Natural organisms cannot reproduce"],"A","Regulation balances benefits with responsible risk management.","Ethical issues"),
]
for x in ethics: add(*x)

# 116-130 statement-based
stmt = [
("Consider the following statements about Bt toxin: 1. It is produced as an inactive protoxin. 2. It is activated in the alkaline insect gut. 3. It forms pores in midgut epithelial cells. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"D","All three describe the NCERT mechanism of Bt toxin.","Bt toxin mechanism"),
("Consider the following statements about cry genes: 1. All cry genes target exactly the same insect. 2. cryIAc and cryIIAb are used against cotton bollworms. 3. cryIAb is useful against corn borer. Which are correct?",["1 only","2 and 3 only","1 and 2 only","1, 2 and 3"],"B","Cry proteins differ in specificity; statements 2 and 3 are correct.","Cry genes"),
("Consider the following statements about RNAi: 1. It is sequence-specific. 2. It is triggered by double-stranded RNA. 3. It enhances translation of the target mRNA. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","RNAi silences rather than enhances target expression.","RNA interference"),
("Consider the following statements about recombinant insulin: 1. Mature insulin contains A and B chains. 2. Proinsulin contains C peptide. 3. C peptide remains in mature insulin. Which are correct?",["1 only","1 and 2 only","2 and 3 only","1, 2 and 3"],"B","C peptide is removed during maturation.","Recombinant insulin"),
("Consider the following statements about ADA gene therapy: 1. Patient lymphocytes may be modified ex vivo. 2. Corrected lymphocytes may require periodic reinfusion. 3. Mature erythrocytes are the ideal permanent target. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","Lymphocytes have limited lifespan; mature red cells are unsuitable permanent targets.","ADA gene therapy"),
("Consider the following statements: 1. PCR amplifies target DNA. 2. ELISA relies on antigen-antibody interaction. 3. A nucleic acid probe binds through complementary base pairing. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"D","All statements accurately describe molecular diagnostic tools.","Molecular diagnosis"),
("Consider the following statements about transgenic animals: 1. They can model human diseases. 2. They may produce useful biological products. 3. They are never used in safety testing. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","Transgenic animals are also used in vaccine and chemical safety testing.","Transgenic animals"),
("Consider the following statements about Rosie: 1. She was a transgenic cow. 2. Her milk contained human alpha-lactalbumin. 3. She produced Bt toxin in milk. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","The Bt-toxin statement is incorrect.","Rosie"),
("Consider the following statements about biopiracy: 1. It may involve traditional knowledge. 2. It may occur without fair compensation. 3. It is identical to approved gene therapy. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","Biopiracy concerns unfair appropriation, not medical gene therapy.","Biopiracy"),
("Consider the following statements about GM crops: 1. They may reduce post-harvest losses. 2. They may improve mineral-use efficiency. 3. Every GM crop produces Bt toxin. Which are correct?",["1 and 2 only","2 and 3 only","1 and 3 only","1, 2 and 3"],"A","GM traits vary; not all GM crops are Bt crops.","GM crops"),
("Statement I: Bt protoxin is activated in the insect gut. Statement II: The insect gut provides an alkaline environment that solubilises the crystal protein.",["Both statements are true, and II explains I","Both are true, but II does not explain I","I is true, II is false","I is false, II is true"],"A","Alkaline pH is central to activation.","Bt toxin mechanism"),
("Statement I: Mature insulin contains C peptide. Statement II: C peptide is removed during proinsulin processing.",["Both statements are true","I is true, II is false","I is false, II is true","Both statements are false"],"C","C peptide is present in proinsulin but absent from mature insulin.","Insulin maturation"),
("Statement I: ELISA can be used to detect an infection. Statement II: ELISA may identify either an antigen or antibodies produced against it.",["Both statements are true, and II explains I","Both are true, but II does not explain I","I is true, II is false","I is false, II is true"],"A","Antigen-antibody detection forms the diagnostic basis.","ELISA"),
("Statement I: Transgenic mice may be used in vaccine safety testing. Statement II: All vaccine testing can therefore be done without any further evaluation.",["Both statements are true","I is true, II is false","I is false, II is true","Both statements are false"],"B","Animal testing is one stage, not the entire evaluation process.","Vaccine safety"),
("Statement I: Patents and biopiracy are synonymous. Statement II: A valid patent is a legal right, whereas biopiracy involves unfair or unauthorised appropriation.",["Both statements are true","I is true, II is false","I is false, II is true","Both statements are false"],"C","The concepts are distinct.","Biopatents and biopiracy"),
]
for x in stmt: add(*x, typ="Statement-based MCQ")

# 131-140 assertion-reason
aropts=[
"Both Assertion and Reason are true, and Reason is the correct explanation of Assertion",
"Both Assertion and Reason are true, but Reason is not the correct explanation of Assertion",
"Assertion is true, but Reason is false",
"Assertion is false, but Reason is true"
]
ars=[
("Assertion: Bt toxin is not active inside Bacillus thuringiensis. Reason: It is synthesised as an inactive protoxin.","A","The protoxin form protects the bacterium from its own insecticidal protein.","Bt toxin"),
("Assertion: Different cry genes may be used against different insect pests. Reason: Cry proteins show target specificity.","A","Specificity explains why different genes are chosen for different pests.","Cry genes"),
("Assertion: RNA interference can protect a transgenic plant against a parasite. Reason: Complementary double-stranded RNA can silence an essential parasite gene.","A","Sequence-specific silencing prevents parasite survival.","RNA interference"),
("Assertion: Animal insulin could sometimes provoke immune reactions in humans. Reason: Animal insulin may differ slightly in amino acid sequence from human insulin.","A","Sequence differences can be immunogenic.","Insulin therapy"),
("Assertion: Corrected lymphocyte therapy for ADA deficiency may not be permanent. Reason: Lymphocytes have a finite lifespan.","A","Loss of corrected cells can necessitate repeated infusions.","ADA gene therapy"),
("Assertion: PCR is useful for early diagnosis. Reason: It can amplify very small quantities of target DNA.","A","Amplification enables detection before pathogen load becomes high.","PCR diagnosis"),
("Assertion: ELISA directly amplifies pathogen DNA. Reason: ELISA is based on antigen-antibody interaction.","D","The assertion is false; the reason is true.","ELISA"),
("Assertion: Transgenic animals can be used to study normal gene function. Reason: Altering expression of a gene can reveal its physiological role.","A","Phenotypic consequences help infer function.","Transgenic animals"),
("Assertion: Biopiracy raises ethical concerns. Reason: Biological resources or traditional knowledge may be commercially used without fair benefit sharing.","A","The reason states the ethical problem.","Biopiracy"),
("Assertion: Every genetically modified organism is automatically safe for unrestricted release. Reason: GM organisms require biosafety evaluation before public use.","D","The assertion is false and the reason is true.","Biosafety"),
]
for x in ars: add(x[0],aropts,x[1],x[2],x[3],typ="Assertion-Reason")

# 141-150 match
matches=[
("Match the gene/product with target or role: I. cryIAc; II. cryIAb; III. dsRNA; IV. ADA cDNA. a. Corn borer; b. Cotton bollworm; c. Gene silencing; d. Correction of ADA deficiency",
["I-b, II-a, III-c, IV-d","I-a, II-b, III-d, IV-c","I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a"],"A","The four pairs follow NCERT examples.","Biotechnology applications"),
("Match the biotechnology product with its source/process: I. Humulin; II. Bt toxin; III. Human alpha-lactalbumin in milk; IV. RNAi-resistant tobacco. a. Transgenic cow Rosie; b. Recombinant E. coli insulin chains; c. cry gene expression; d. Sense and antisense RNA",
["I-b, II-c, III-a, IV-d","I-c, II-b, III-d, IV-a","I-a, II-d, III-c, IV-b","I-d, II-a, III-b, IV-c"],"A","Each product or trait is matched with its production strategy.","Products and processes"),
("Match the diagnostic method with principle: I. PCR; II. ELISA; III. Nucleic acid probe; IV. Autoradiography. a. Antigen-antibody binding; b. Amplification; c. Complementary hybridisation; d. Detection of radioactive signal",
["I-b, II-a, III-c, IV-d","I-a, II-b, III-d, IV-c","I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a"],"A","These are the defining principles of the methods.","Molecular diagnosis"),
("Match the transgenic-animal use with example: I. Disease model; II. Biological product; III. Vaccine safety; IV. Chemical safety. a. Rosie; b. Polio vaccine testing in mice; c. Cancer model; d. Enhanced sensitivity to toxic substances",
["I-c, II-a, III-b, IV-d","I-a, II-c, III-d, IV-b","I-b, II-d, III-a, IV-c","I-d, II-b, III-c, IV-a"],"A","The examples correspond to the four NCERT uses.","Transgenic animals"),
("Match the term with description: I. Biopatent; II. Biopiracy; III. GEAC; IV. Benefit sharing. a. Regulatory biosafety evaluation; b. Legal protection of biological invention; c. Equitable returns to knowledge/resource providers; d. Unfair appropriation",
["I-b, II-d, III-a, IV-c","I-d, II-b, III-c, IV-a","I-a, II-c, III-d, IV-b","I-c, II-a, III-b, IV-d"],"A","Each term is paired with its correct meaning.","Ethical issues"),
("Match the insulin-related term with description: I. Proinsulin; II. Mature insulin; III. C peptide; IV. Humulin. a. Removed during processing; b. Recombinant human insulin; c. A and B chains plus connecting segment; d. A and B chains linked by disulfide bonds",
["I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a","I-a, II-b, III-c, IV-d","I-b, II-a, III-d, IV-c"],"A","The structural and therapeutic terms are correctly paired.","Recombinant insulin"),
("Match the application with organism: I. Bt cotton; II. RNAi tobacco; III. Recombinant insulin production; IV. Rosie. a. E. coli; b. Transgenic cow; c. Bacillus-derived cry gene; d. Meloidogyne resistance",
["I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a","I-a, II-b, III-c, IV-d","I-b, II-a, III-d, IV-c"],"A","Each application is linked to its key organism or biological source.","Applications"),
("Match the example with issue/application: I. Turmeric; II. Basmati; III. Neem; IV. ADA deficiency. a. Gene therapy; b. Wound-healing patent dispute; c. Rice intellectual-property controversy; d. Pesticidal-use patent controversy",
["I-b, II-c, III-d, IV-a","I-c, II-d, III-a, IV-b","I-d, II-a, III-b, IV-c","I-a, II-b, III-c, IV-d"],"A","The first three are biopiracy/patent examples; ADA is a gene-therapy example.","Biopiracy and gene therapy"),
("Match the step with outcome in Bt action: I. Ingestion; II. Alkaline solubilisation; III. Receptor binding; IV. Pore formation. a. Entry into insect gut; b. Protoxin activation; c. Attachment to midgut epithelium; d. Cell swelling and lysis",
["I-a, II-b, III-c, IV-d","I-b, II-a, III-d, IV-c","I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a"],"A","This is the correct mechanistic sequence.","Bt toxin mechanism"),
("Match the therapy/tool with limitation or strength: I. Enzyme replacement for ADA; II. Lymphocyte gene therapy; III. PCR; IV. ELISA. a. May require repeated enzyme doses; b. May require repeated cell infusions; c. Detects minute DNA amounts; d. Detects antigen-antibody interaction",
["I-a, II-b, III-c, IV-d","I-b, II-a, III-d, IV-c","I-c, II-d, III-a, IV-b","I-d, II-c, III-b, IV-a"],"A","The pairs summarise key advantages or limitations.","Clinical biotechnology"),
]
for x in matches: add(*x, typ="Match the Following")


print(json.dumps(qs))