/**
 * Question Controller
 */

const Question = require('../models/Question');
const PDFExtractor = require('../services/pdfExtractor');
const { getGeminiText } = require('../services/geminiClient');
const cloudinary = require('cloudinary').v2;
const path = require('path');

// Basic CRUD and query operations (needed by routes)
exports.getQuestions = async (req, res) => {
  try {
    const { subject, chapter, topic, difficulty, source, search, page = 1, limit = 20 } = req.query;
    const safeLimit = Math.min(100, Math.max(1, Number(limit) || 20));
    const skip = (Math.max(1, Number(page) || 1) - 1) * safeLimit;
    const query = { isPublished: true };
    if (subject) query.subject = subject;
    if (chapter) query.chapter = chapter;
    if (topic) query.topic = topic;
    if (difficulty) query.difficulty = difficulty;
    if (source) query.source = source;
    if (search) {
      const pattern = new RegExp(String(search).trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      query.$or = [{ questionText: pattern }, { chapter: pattern }, { topic: pattern }];
    }

    const [questions, total] = await Promise.all([
      Question.find(query).skip(skip).limit(safeLimit),
      Question.countDocuments(query)
    ]);

    res.status(200).json({ success: true, data: questions, pagination: { total, page: Number(page), pages: Math.ceil(total / safeLimit) } });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.getQuestion = async (req, res) => {
  try {
    const q = await Question.findById(req.params.id);
    if (!q) return res.status(404).json({ success: false, message: 'Question not found' });
    res.status(200).json({ success: true, data: q });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.createQuestion = async (req, res) => {
  try {
    const payload = req.body || {};
    const q = await Question.create({ ...payload, uploadedBy: req.userId, isPublished: false });
    res.status(201).json({ success: true, data: q });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.updateQuestion = async (req, res) => {
  try {
    const q = await Question.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
    if (!q) return res.status(404).json({ success: false, message: 'Question not found' });
    res.status(200).json({ success: true, data: q });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.deleteQuestion = async (req, res) => {
  try {
    const q = await Question.findByIdAndDelete(req.params.id);
    if (!q) return res.status(404).json({ success: false, message: 'Question not found' });
    res.status(200).json({ success: true, message: 'Deleted' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.publishQuestion = async (req, res) => {
  try {
    const q = await Question.findByIdAndUpdate(req.params.id, { isPublished: true, isVerified: true, verifiedBy: req.userId, verifiedAt: new Date() }, { new: true });
    if (!q) return res.status(404).json({ success: false, message: 'Question not found' });
    res.status(200).json({ success: true, data: q });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// @route   POST /api/questions/generate
// @desc    AI generates NEET questions (MCQ, Assertion-Reason, Match, Statement)
//          including PYQ-style and predicted questions, with full classification.
// @access  Private/Admin
// ─────────────────────────────────────────────────────────────────────────────
exports.generateQuestions = async (req, res) => {
  try {
    const aiService = require('../services/aiQuestionGenerator');
    const {
      subject = 'biology',
      chapter = '',
      topic = '',
      questionTypes = ['mcq'],
      count = 10,
      includePYQ = true,
      includePredicted = true,
      difficulty = 'mixed',
      source = 'custom'
    } = req.body || {};

    const candidates = await aiService.generateQuestions({
      subject, chapter, topic,
      questionTypes, count, includePYQ, includePredicted, difficulty, source
    });

    if (!Array.isArray(candidates) || candidates.length === 0) {
      return res.status(502).json({ success: false, message: 'AI returned no questions' });
    }

    // Attach uploader and save as drafts
    const toSave = candidates.map(q => ({ ...q, uploadedBy: req.userId }));
    const saved = await Question.insertMany(toSave);

    res.status(201).json({
      success: true,
      message: `${saved.length} questions generated by AI and saved as drafts. Review before publishing.`,
      data: saved
    });
  } catch (error) {
    console.error('❌ AI Generate Error:', error);
    res.status(500).json({ success: false, message: error.message || 'AI generation failed' });
  }
};

// Stream generation: call the AI repeatedly for single-question outputs and stream each saved draft via SSE
exports.generateQuestionsStream = async (req, res) => {
  try {
    const aiService = require('../services/aiQuestionGenerator');
    const {
      subject = 'biology',
      chapter = '',
      topic = '',
      questionTypes = ['mcq'],
      count = 10,
      includePYQ = true,
      includePredicted = true,
      difficulty = 'mixed',
      source = 'custom'
    } = req.body || {};

    const total = Math.max(1, Math.min(50, Number(count) || 10));

    // SSE headers
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive'
    });
    res.flushHeaders?.();

    let idx = 0;
    for (idx = 1; idx <= total; idx++) {
      // If client closed connection, stop
      if (res.finished) break;

      // Request one question at a time from AI
      let candidates;
      try {
        candidates = await aiService.generateCandidates({ subject, chapter, topic, difficulty, count: 1 });
      } catch (err) {
        const payload = { type: 'error', index: idx, total, message: err.message };
        res.write(`event: error\ndata: ${JSON.stringify(payload)}\n\n`);
        break;
      }

      const q = Array.isArray(candidates) && candidates[0] ? candidates[0] : null;
      if (!q) {
        const payload = { type: 'skipped', index: idx, total, message: 'AI returned no question' };
        res.write(`event: skipped\ndata: ${JSON.stringify(payload)}\n\n`);
        continue;
      }

      // Normalize to DB shape similar to generateQuestions
      const OPTION_KEYS = ['A', 'B', 'C', 'D'];
      const options = {};
      OPTION_KEYS.forEach((k, i) => {
        const keyText = q.options?.[k]?.text || (q.options && q.options[i] && q.options[i].text) || `Option ${k}`;
        options[k] = { text: String(keyText).trim() };
      });

      const savedObj = {
        questionText: q.questionText || `AI generated question ${idx}`,
        options,
        correctAnswer: q.correctAnswer && ['A','B','C','D'].includes(q.correctAnswer) ? q.correctAnswer : 'A',
        explanation: { text: q.explanation || '' },
        subject: (subject || 'biology').toLowerCase(),
        chapter: q.chapter || chapter || 'Unclassified',
        topic: q.topic || topic || '',
        type: q.type || 'mcq',
        difficulty: q.difficulty || difficulty === 'mixed' ? 'medium' : difficulty,
        source: q.source || (q.isLikelyPYQ ? 'pyq' : source),
        sourceDetails: { year: q.yearSeen || undefined, examType: 'neet' },
        pyq: { isPYQ: Boolean(q.isLikelyPYQ), reference: q.isLikelyPYQ ? `NEET ${q.yearSeen || 'PYQ'}` : undefined },
        assertion: q.assertion || null,
        generatedByAI: true,
        aiMetadata: { generatedAt: new Date(), confidence: q.confidenceScore },
        trendingFrequency: q.difficulty === 'hard' ? 'high' : q.difficulty === 'easy' ? 'low' : 'medium',
        inSyllabus: true,
        tags: ['ai-generated', q.type || 'mcq', q.difficulty || 'medium'],
        qualityScore: q.qualityScore || 70,
        isPublished: false,
        review: { status: 'pending' },
        uploadedBy: req.userId
      };

      try {
        const saved = await Question.create(savedObj);
        const payload = { type: 'question', index: idx, total, data: saved };
        res.write(`event: question\ndata: ${JSON.stringify(payload)}\n\n`);
      } catch (saveErr) {
        const payload = { type: 'error', index: idx, total, message: saveErr.message };
        res.write(`event: error\ndata: ${JSON.stringify(payload)}\n\n`);
      }
    }

    // Final event
    res.write(`event: done\ndata: ${JSON.stringify({ total: idx - 1 })}\n\n`);
    res.end();
  } catch (error) {
    console.error('❌ Stream Generate Error:', error);
    if (!res.headersSent) res.status(500).json({ success: false, message: error.message });
    else {
      try {
        res.write(`event: error\ndata: ${JSON.stringify({ message: error.message })}\n\n`);
        res.end();
      } catch (e) {}
    }
  }
};
// @route   POST /api/questions/:id/ai-fix
// @desc    Use AI to clean up a garbled question AND classify difficulty/topic/chapter
// @access  Private/Admin
exports.aiFixQuestion = async (req, res) => {
  try {
    const question = await Question.findById(req.params.id);
    if (!question) {
      return res.status(404).json({ success: false, message: 'Question not found' });
    }

    const { PHYSICS_CHAPTERS, CHEMISTRY_CHAPTERS, BIOLOGY_CHAPTERS } = require('../config/constants');
    const chapterMap = {
      physics: PHYSICS_CHAPTERS, chemistry: CHEMISTRY_CHAPTERS,
      biology: BIOLOGY_CHAPTERS, botany: BIOLOGY_CHAPTERS, zoology: BIOLOGY_CHAPTERS
    };
    const chapterList = (chapterMap[(question.subject || '').toLowerCase()] || [
      ...PHYSICS_CHAPTERS, ...CHEMISTRY_CHAPTERS, ...BIOLOGY_CHAPTERS
    ]).join(', ');

    const optionsText = ['A', 'B', 'C', 'D']
      .map(k => `${k}: ${question.options?.[k]?.text || ''}`)
      .join('\n');

    const prompt = `You are a NEET question editor and classifier. The question below may have garbled text from PDF extraction. Do two things in one pass:

1. CLEAN the question — fix garbled text, truncated content, bleeding answer explanations.
2. CLASSIFY the question — assign difficulty, topic, and the best NEET NCERT chapter.

Subject: ${question.subject}
Current question stem: ${question.questionText}
Current options:
${optionsText}
Current correct answer: ${question.correctAnswer}

NEET Chapter list: ${chapterList}

Rules:
1. Return ONLY valid JSON, no markdown.
2. "questionText" — clean, complete question sentence only.
3. Each option A/B/C/D — only the option text, no trailing explanation.
4. "correctAnswer" — A, B, C, or D. Deduce from context if missing.
5. "explanation" — concise 1-2 sentence explanation of the correct answer.
6. "difficulty" — "easy", "medium", or "hard" based on NEET standards.
7. "topic" — specific sub-topic or concept being tested (e.g. "Food chain", "Ohm's Law").
8. "chapter" — best matching NCERT chapter from the list above.
9. If you cannot fix this question at all, return {"error": "cannot fix"}.

Return exactly:
{"questionText":"...","options":{"A":{"text":"..."},"B":{"text":"..."},"C":{"text":"..."},"D":{"text":"..."}},"correctAnswer":"A","explanation":"...","difficulty":"medium","topic":"...","chapter":"..."}`;

    let fixed;
    try {
      const content = await getGeminiText({
        prompt,
        maxOutputTokens: 1000,
        temperature: 0.1,
        responseMimeType: 'application/json'
      });

      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error('No JSON in response');
      fixed = JSON.parse(jsonMatch[0]);
      if (fixed.error) throw new Error(fixed.error);
    } catch (aiError) {
      return res.status(422).json({
        success: false,
        message: `AI could not fix this question: ${aiError.message}`
      });
    }

    const OPTION_KEYS = ['A', 'B', 'C', 'D'];
    const hasAllOptions = OPTION_KEYS.every(k => fixed.options?.[k]?.text?.trim().length > 0);
    const hasValidAnswer = OPTION_KEYS.includes(fixed.correctAnswer);
    if (!fixed.questionText?.trim() || !hasAllOptions || !hasValidAnswer) {
      return res.status(422).json({
        success: false,
        message: 'AI returned incomplete question data. Please fix manually.'
      });
    }

    const validDifficulty = ['easy', 'medium', 'hard'].includes(fixed.difficulty) ? fixed.difficulty : (question.difficulty || 'medium');

    const updated = await Question.findByIdAndUpdate(
      req.params.id,
      {
        questionText: fixed.questionText.trim(),
        options: Object.fromEntries(
          OPTION_KEYS.map(k => [k, { text: fixed.options[k].text.trim(), image: question.options?.[k]?.image }])
        ),
        correctAnswer: fixed.correctAnswer,
        explanation: fixed.explanation ? { text: fixed.explanation } : question.explanation,
        difficulty: validDifficulty,
        topic: fixed.topic?.trim() || question.topic || '',
        chapter: fixed.chapter?.trim() || question.chapter || 'Unclassified',
        tags: [...new Set([...(question.tags || []).filter(t => t !== 'raw-import'), 'ai-fixed'])]
      },
      { new: true, runValidators: true }
    );

    res.status(200).json({
      success: true,
      message: 'Question fixed and classified by AI.',
      data: updated
    });

  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};


// @route   POST /api/questions/upload-pdf
// @desc    Upload PDF for question extraction (Admin only)
// @access  Private/Admin
exports.uploadPDF = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: 'No file uploaded'
      });
    }

    const { subject, chapter, topic, source, testType, year, allowLocalOcr, useAiParsing } = req.body;

    const { questions, images } = await PDFExtractor.parseQuestionsFromFile(req.file, {
      subject,
      chapter,
      topic,
      source,
      sourceDetails: {
        year: year ? Number(year) : undefined,
        testName: req.file.originalname,
        examType: testType
      }
    }, {
      allowLocalOcr: allowLocalOcr === 'true',
      useAiParsing: useAiParsing === 'true'
    });

    // Save questions to database
    const savedQuestions = await Question.insertMany(
      questions.map(q => ({
        ...q,
        uploadedBy: req.userId,
        isPublished: false
      }))
    );

    // ── Auto-classify: let AI assign difficulty, topic, chapter right away ──
    // Run silently in the background — failures don't block the response.
    const autoClassify = async () => {
      const batchSize = 20;
      for (let i = 0; i < savedQuestions.length; i += batchSize) {
        const batch = savedQuestions.slice(i, i + batchSize);
        try {
          const classifications = await PDFExtractor.classifyQuestionBatch(batch);
          const byId = new Map(classifications.map(item => [String(item.id), item]));
          for (const q of batch) {
            const c = byId.get(String(q._id));
            if (!c) continue;
            const tags = Array.from(new Set([
              ...(q.tags || []).filter(t => t !== 'raw-import'),
              ...(c.tags || []),
              'ai-classified'
            ])).filter(Boolean);
            await Question.findByIdAndUpdate(q._id, {
              difficulty: c.difficulty,
              topic: c.topic,
              chapter: c.chapter || q.chapter,
              learningObjective: c.learningObjective,
              commonMistake: c.commonMistake,
              tags
            });
          }
        } catch (classifyErr) {
          console.warn(`[Auto-classify] Batch ${Math.floor(i / batchSize) + 1} failed:`, classifyErr.message);
        }
      }
    };

    // Fire-and-forget — don't await so the HTTP response returns immediately
    autoClassify().catch(err => console.warn('[Auto-classify] Error:', err.message));

    res.status(201).json({
      success: true,
      message: `${savedQuestions.length} questions extracted and saved. AI is classifying difficulty & topics in the background.`,
      data: savedQuestions,
      extractedImages: images || []
    });
  } catch (error) {
    console.error('❌ PDF Upload Error:', error);
    const message = error.message || 'PDF processing failed';
    const { getProvider } = require('../services/geminiClient');
    const provider = getProvider();

    const isQuotaError = error.status === 429 ||
      /throttl|quota|rate limit|too many requests|retry after|insufficient/i.test(message);

    const isAccessError = /access denied|not authorized|AccessDenied|permission|InvokeModel|authentication|api.key/i.test(message);

    const isExpectedImportError = isQuotaError || isAccessError ||
      /API_KEY|AI question extraction|API key|model|scanned|OCR|extract text|parse questions|No valid JSON|PDF|unsupported|empty|OpenAI|Bedrock|Gemini/i.test(message);

    let action = message;
    if (isQuotaError) {
      if (provider === 'openai') {
        action = 'OpenAI rate limit or quota exceeded. Please check billing/limits at https://platform.openai.com/account/billing';
      } else if (provider === 'bedrock') {
        action = 'AWS Bedrock throttling limit reached. Please request a model invocation quota increase in the AWS Bedrock Console.';
      } else {
        action = 'Gemini rate limit exceeded. Wait a moment and retry, or request quota in Google AI Studio.';
      }
    } else if (isAccessError) {
      if (provider === 'openai') {
        action = 'OpenAI authentication failed. Set a valid OPENAI_API_KEY in backend/.env starting with "sk-".';
      } else if (provider === 'bedrock') {
        action = 'AWS Bedrock access denied. Check bedrock:InvokeModel permission and enable Claude 3 Haiku in Model Access (us-east-1).';
      } else {
        action = 'Gemini authentication failed. Set a valid GEMINI_API_KEY in backend/.env.';
      }
    } else if (/poppler|pdftoppm|renderer|local OCR/i.test(message)) {
      action = 'Install Poppler so local OCR can render scanned PDF pages, set PDF_RENDERER_PATH in backend/.env.';
    } else if (message.toLowerCase().includes('scanned')) {
      action = 'This PDF is scanned/image-based. Use a selectable-text PDF, or add questions manually.';
    }

    res.status(isQuotaError ? 429 : isExpectedImportError ? 400 : 500).json({
      success: false,
      message,
      action,
      retryAfter: error.retryAfter
    });
  } finally {
    if (req.file?.path) {
      const fs = require('fs');
      fs.unlink(req.file.path, () => {});
    }
  }
};

exports.uploadImage = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: 'No image uploaded'
      });
    }

    const relativeUrl = `/uploads/${path.basename(req.file.path)}`;

    res.status(201).json({
      success: true,
      message: 'Image uploaded successfully',
      data: {
        url: `${req.protocol}://${req.get('host')}${relativeUrl}`,
        publicId: req.file.filename,
        localPath: relativeUrl
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Image upload failed'
    });
  }
};

// @route   POST /api/questions/classify
// @desc    Classify saved questions in Gemini batches (Admin only)
// @access  Private/Admin
exports.classifyQuestions = async (req, res) => {
  try {
    const {
      questionIds,
      ids,
      subject,
      source,
      onlyUnclassified = true,
      limit = 500,
      batchSize = 50,
      publish = false
    } = req.body || {};

    const selectedIds = Array.isArray(questionIds) ? questionIds : Array.isArray(ids) ? ids : [];
    const safeLimit = Math.min(500, Math.max(1, Number(limit) || 500));
    const safeBatchSize = Math.min(50, Math.max(1, Number(batchSize) || 50));
    const query = {};

    if (selectedIds.length) {
      query._id = { $in: selectedIds };
    } else {
      if (subject) query.subject = subject;
      if (source) query.source = source;
      if (onlyUnclassified !== false) {
        query.$or = [
          { chapter: { $in: ['', 'Unclassified'] } },
          { topic: { $in: ['', null] } },
          { tags: 'raw-import' }
        ];
      }
    }

    const questions = await Question.find(query)
      .sort({ createdAt: -1 })
      .limit(safeLimit)
      .select('_id questionText options subject chapter topic difficulty tags learningObjective commonMistake');

    if (!questions.length) {
      return res.status(200).json({
        success: true,
        message: 'No questions matched the classification filter',
        data: { matched: 0, updated: 0, batches: 0 }
      });
    }

    let updated = 0;
    const failures = [];

    for (let index = 0; index < questions.length; index += safeBatchSize) {
      const batch = questions.slice(index, index + safeBatchSize);
      const classifications = await PDFExtractor.classifyQuestionBatch(batch);
      const byId = new Map(classifications.map(item => [String(item.id), item]));

      for (const question of batch) {
        const classification = byId.get(String(question._id));
        if (!classification) {
          failures.push({ id: String(question._id), reason: 'No classification returned' });
          continue;
        }

        let tags = Array.from(new Set([
          ...(question.tags || []),
          ...classification.tags,
          'ai-classified'
        ])).filter(Boolean);

        const needsAnswerReview = tags.includes('needs-answer-review') || question.sourceDetails?.needsAnswerReview;

        const updateObj = {
          chapter: classification.chapter,
          topic: classification.topic,
          difficulty: classification.difficulty,
          learningObjective: classification.learningObjective,
          commonMistake: classification.commonMistake,
          inSyllabus: classification.inSyllabus !== false,
          trendingFrequency: classification.trendingFrequency || 'medium'
        };

        if (classification.correctAnswer && (needsAnswerReview || !question.explanation?.text)) {
          updateObj.correctAnswer = classification.correctAnswer;
          updateObj.explanation = { text: classification.explanation || '' };
          // Remove the review flags now that AI solved it
          tags = tags.filter(t => t !== 'needs-answer-review');
          if (updateObj.sourceDetails) {
            updateObj.sourceDetails.needsAnswerReview = false;
          }
        }

        updateObj.tags = tags;

        if (publish) {
          updateObj.isPublished = true;
          updateObj.isVerified = true;
          updateObj.verifiedAt = new Date();
          if (req.user?._id) {
            updateObj.verifiedBy = req.user._id;
          }
        }

        await Question.findByIdAndUpdate(question._id, updateObj, { runValidators: true });

        updated += 1;
      }
    }

    res.status(200).json({
      success: true,
      message: `${updated} questions classified${publish ? ' and published' : ''}`,
      data: {
        matched: questions.length,
        updated,
        batches: Math.ceil(questions.length / safeBatchSize),
        failures
      }
    });
  } catch (error) {
    const message = error.message || 'Question classification failed';
    const isQuotaError = error.status === 429 || /quota|rate limit|retry after|too many requests/i.test(message);

    res.status(isQuotaError ? 429 : 500).json({
      success: false,
      message,
      action: isQuotaError
        ? 'Gemini quota is exhausted. Retry later, lower batchSize/limit, or request quota in Google AI Studio.'
        : 'Check backend logs and Gemini configuration.',
      retryAfter: error.retryAfter
    });
  }
};

// @route   DELETE /api/questions/admin/clear-all
// @desc    Delete questions selectively or all (admin only)
// @access  Private/Admin
exports.clearAllQuestions = async (req, res) => {
  try {
    const mongoose = require('mongoose');
    const { subject, chapter, topic, status } = req.query;

    const query = {};
    if (subject) query.subject = subject.toLowerCase().trim();
    if (chapter) query.chapter = chapter.trim();
    if (topic) query.topic = topic.trim();

    if (status === 'draft') {
      query.isPublished = false;
    } else if (status === 'published') {
      query.isPublished = true;
    }

    const questionResult = await Question.deleteMany(query);
    let attemptCount = 0;

    // Only clear attempts/tests if doing a complete database wipe (no filters)
    const isFullClear = !subject && !chapter && !topic && (!status || status === 'all');
    if (isFullClear) {
      if (mongoose.connection.collections['testattempts']) {
        const r = await mongoose.connection.collections['testattempts'].deleteMany({});
        attemptCount = r.deletedCount || 0;
      }
      if (mongoose.connection.collections['tests']) {
        await mongoose.connection.collections['tests'].deleteMany({});
      }
    }

    res.status(200).json({
      success: true,
      message: `Cleared ${questionResult.deletedCount} questions.${isFullClear ? ` Also cleared ${attemptCount} test attempts.` : ''}`,
      data: { questionsDeleted: questionResult.deletedCount, attemptsDeleted: attemptCount }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @route   GET /api/questions/stats
// @desc    Get question statistics
// @access  Public
exports.getQuestionStats = async (req, res) => {
  try {
    const bySubject = await Question.aggregate([
      { $match: { isPublished: true } },
      {
        $group: {
          _id: '$subject',
          count: { $sum: 1 }
        }
      }
    ]);

    res.status(200).json({
      success: true,
      data: {
        totalPublished: await Question.countDocuments({ isPublished: true }),
        totalPending: await Question.countDocuments({ isPublished: false }),
        bySubject
      }
    });

  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

exports.getQuestionMetadata = async (req, res) => {
  try {
    const rows = await Question.aggregate([
      { $match: { isPublished: true } },
      {
        $group: {
          _id: {
            subject: '$subject',
            chapter: '$chapter',
            topic: '$topic',
            difficulty: '$difficulty',
            source: '$source'
          },
          count: { $sum: 1 }
        }
      },
      { $sort: { '_id.subject': 1, '_id.chapter': 1, '_id.topic': 1 } }
    ]);

    res.status(200).json({ success: true, data: rows });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.getAdminQuestions = async (req, res) => {
  try {
    const { status = 'pending', page = 1, limit = 50, search, subject, chapter } = req.query;
    
    let query = {};
    if (status === 'pending') {
      query.isPublished = false;
    } else if (status === 'published') {
      query.isPublished = true;
    }

    if (subject) {
      query.subject = subject.toLowerCase();
    }
    if (chapter) {
      query.chapter = chapter;
    }

    if (search && String(search).trim()) {
      const pattern = new RegExp(String(search).trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      query.$or = [
        { questionText: pattern },
        { chapter: pattern },
        { topic: pattern }
      ];
    }

    const skip = (Number(page) - 1) * Number(limit);
    const [questions, total] = await Promise.all([
      Question.find(query).sort({ createdAt: -1 }).skip(skip).limit(Number(limit)),
      Question.countDocuments(query)
    ]);
    res.status(200).json({
      success: true,
      data: questions,
      pagination: { total, page: Number(page), pages: Math.ceil(total / Number(limit)) }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// @route   POST /api/questions/generate
// @desc    AI generates NEET questions (MCQ, Assertion-Reason, Match, Statement)
//          including PYQ-style and predicted questions, with full classification.
// @access  Private/Admin
// ─────────────────────────────────────────────────────────────────────────────
exports.generateQuestions = async (req, res) => {
  try {
    const {
      subject = 'biology',
      chapter = '',
      topic = '',
      questionTypes = ['mcq'],       // ['mcq','assertion_reason','match_following','statement_based']
      count = 10,                    // per type
      includePYQ = true,             // include PYQ-style questions
      includePredicted = true,       // include predicted/likely questions
      difficulty = 'mixed',          // 'easy'|'medium'|'hard'|'mixed'
      source = 'custom'
    } = req.body;

    const { PHYSICS_CHAPTERS, CHEMISTRY_CHAPTERS, BIOLOGY_CHAPTERS } = require('../config/constants');
    const chapterMap = {
      physics: PHYSICS_CHAPTERS, chemistry: CHEMISTRY_CHAPTERS,
      biology: BIOLOGY_CHAPTERS, botany: BIOLOGY_CHAPTERS, zoology: BIOLOGY_CHAPTERS
    };
    const chapterList = (chapterMap[subject.toLowerCase()] || []).join(', ');

    const safeCount = Math.min(20, Math.max(1, Number(count) || 10));
    const safeTypes = Array.isArray(questionTypes) ? questionTypes : [questionTypes];

    const difficultyInstruction = difficulty === 'mixed'
      ? 'Distribute difficulty: roughly 30% easy, 40% medium, 30% hard.'
      : `All questions should be ${difficulty} difficulty.`;

    // Build a type-specific prompt section
    const typeInstructions = {
      mcq: `
MCQ FORMAT:
{
  "type": "mcq",
  "questionText": "Complete question stem",
  "options": {"A":{"text":"..."},"B":{"text":"..."},"C":{"text":"..."},"D":{"text":"..."}},
  "correctAnswer": "A",
  "explanation": "Why the answer is correct",
  "difficulty": "easy|medium|hard",
  "topic": "specific sub-topic",
  "isLikelyPYQ": true/false,
  "yearSeen": 2023
}`,
      assertion_reason: `
ASSERTION-REASON FORMAT:
Assertion (A): [statement]
Reason (R): [statement]
Options MUST always be:
A: Both A and R are true and R is the correct explanation of A
B: Both A and R are true but R is not the correct explanation of A
C: A is true but R is false
D: A is false but R is true
{
  "type": "assertion_reason",
  "questionText": "Assertion (A): ...\\nReason (R): ...",
  "options": {
    "A": {"text": "Both A and R are true and R is the correct explanation of A"},
    "B": {"text": "Both A and R are true but R is not the correct explanation of A"},
    "C": {"text": "A is true but R is false"},
    "D": {"text": "A is false but R is true"}
  },
  "correctAnswer": "A|B|C|D",
  "explanation": "...",
  "difficulty": "easy|medium|hard",
  "topic": "...",
  "isLikelyPYQ": true/false
}`,
      match_following: `
MATCH THE FOLLOWING FORMAT:
Column I has items 1-4, Column II has items a-d.
{
  "type": "match_following",
  "questionText": "Match Column I with Column II:\\nColumn I\\n1. [item]\\n2. [item]\\n3. [item]\\n4. [item]\\nColumn II\\na. [match]\\nb. [match]\\nc. [match]\\nd. [match]",
  "options": {
    "A": {"text": "1-a, 2-b, 3-c, 4-d"},
    "B": {"text": "1-b, 2-a, 3-d, 4-c"},
    "C": {"text": "1-c, 2-d, 3-a, 4-b"},
    "D": {"text": "1-d, 2-c, 3-b, 4-a"}
  },
  "correctAnswer": "A|B|C|D",
  "explanation": "...",
  "difficulty": "easy|medium|hard",
  "topic": "...",
  "isLikelyPYQ": false
}`,
      statement_based: `
STATEMENT-BASED FORMAT (multiple true/false statements):
{
  "type": "statement_based",
  "questionText": "Which of the following statements are correct?\\n1. [statement]\\n2. [statement]\\n3. [statement]\\n4. [statement]",
  "options": {
    "A": {"text": "1 and 2 only"},
    "B": {"text": "2 and 3 only"},
    "C": {"text": "1, 2 and 3 only"},
    "D": {"text": "All of the above"}
  },
  "correctAnswer": "A|B|C|D",
  "explanation": "...",
  "difficulty": "easy|medium|hard",
  "topic": "...",
  "isLikelyPYQ": false
}`
    };

    const requestedTypeInstructions = safeTypes
      .map(t => typeInstructions[t] || typeInstructions.mcq)
      .join('\n\n');

    const pyqInstruction = includePYQ
      ? `- Include some questions that are actual PYQ-style (previously asked in NEET 2017-2024). Set "isLikelyPYQ": true and "yearSeen" for those.`
      : '';

    const predictedInstruction = includePredicted
      ? `- Include some predicted questions that are highly likely to appear in upcoming NEET based on recent trends and NTA patterns.`
      : '';

    const prompt = `You are an expert NEET question setter with deep knowledge of NCERT syllabus and NEET exam patterns.

Generate ${safeCount} high-quality NEET questions for:
- Subject: ${subject.toUpperCase()}
- Chapter: ${chapter || 'Any chapter from ' + subject}
- Topic: ${topic || 'Any topic in the chapter'}
- Types requested: ${safeTypes.join(', ')}
- ${difficultyInstruction}
${pyqInstruction}
${predictedInstruction}

IMPORTANT RULES:
1. Questions must be 100% NCERT-based and NEET-relevant.
2. All options must be scientifically accurate.
3. Explanation must be detailed enough for a student to understand why.
4. "topic" must be the specific concept tested (e.g., "Krebs Cycle", "Ohm's Law", "Mole Concept").
5. "difficulty": easy = recall/direct NCERT, medium = application, hard = multi-concept/analysis.
6. Return ONLY a valid JSON array — no markdown, no extra text.
7. For MCQ: all 4 options must be plausible but only one correct.
8. Available NEET chapters for chapter classification: ${chapterList}

QUESTION FORMAT for each type:
${requestedTypeInstructions}

Return a JSON array of exactly ${safeCount} questions:
[{ ... }, { ... }, ...]`;

    const content = await getGeminiText({
      systemInstruction: 'You are an expert NEET exam question setter. Return only valid JSON arrays.',
      prompt,
      maxOutputTokens: 4096,
      temperature: 0.7,
      responseMimeType: 'application/json'
    });

    // Parse AI response
    const jsonMatch = content.match(/\[[\s\S]*\]/);
    if (!jsonMatch) throw new Error('AI did not return a valid JSON array.');
    const generated = JSON.parse(jsonMatch[0]);

    if (!Array.isArray(generated) || generated.length === 0) {
      throw new Error('AI returned an empty question list.');
    }

    const OPTION_KEYS = ['A', 'B', 'C', 'D'];
    const validDifficulties = ['easy', 'medium', 'hard'];
    const validTypes = ['mcq', 'assertion_reason', 'match_following', 'statement_based', 'numerical'];

    // Normalize and validate each generated question
    const normalized = generated.map((q, idx) => {
      const qType = validTypes.includes(q.type) ? q.type : 'mcq';
      const qDiff = validDifficulties.includes(q.difficulty) ? q.difficulty : 'medium';

      // Ensure all 4 options exist
      const options = {};
      OPTION_KEYS.forEach(k => {
        options[k] = { text: q.options?.[k]?.text?.trim() || `Option ${k}` };
      });

      const correctAnswer = OPTION_KEYS.includes(q.correctAnswer) ? q.correctAnswer : 'A';

      const assertion = {
        isAssertionReason: qType === 'assertion_reason',
        assertionText: '',
        reasonText: '',
        pairIsCorrect: typeof q.pairIsCorrect === 'boolean' ? q.pairIsCorrect : undefined
      };
      if (qType === 'assertion_reason' && typeof q.questionText === 'string') {
        const assertionMatch = q.questionText.match(/Assertion\s*[:\-]?\s*(.+?)\s*(?=Reason|R\s*[:\-]?)/is);
        const reasonMatch = q.questionText.match(/Reason\s*[:\-]?\s*(.+)$/is);
        assertion.assertionText = assertionMatch ? assertionMatch[1].trim() : '';
        assertion.reasonText = reasonMatch ? reasonMatch[1].trim() : '';
      }
      if (qType !== 'assertion_reason') {
        assertion.isAssertionReason = false;
      }

      const questionText = (q.questionText || `Question ${idx + 1}`).trim();
      const pyqMeta = {
        isPYQ: Boolean(q.isLikelyPYQ),
        reference: q.isLikelyPYQ ? `NEET ${q.yearSeen || 'Recent PYQ'}` : undefined
      };

      return {
        questionText,
        options,
        correctAnswer,
        explanation: { text: q.explanation?.trim() || '' },
        subject: subject.toLowerCase(),
        chapter: q.chapter?.trim() || chapter || 'Unclassified',
        topic: q.topic?.trim() || topic || '',
        type: qType,
        difficulty: qDiff,
        source: q.isLikelyPYQ ? 'pyq' : source,
        sourceDetails: {
          year: q.yearSeen || undefined,
          examType: 'neet'
        },
        pyq: pyqMeta,
        assertion,
        generatedByAI: true,
        aiMetadata: {
          generatedAt: new Date()
        },
        trendingFrequency: qDiff === 'hard' ? 'high' : qDiff === 'easy' ? 'low' : 'medium',
        inSyllabus: true,
        tags: [
          'ai-generated',
          qType,
          qDiff,
          ...(q.isLikelyPYQ ? ['pyq-style'] : []),
          ...(includePredicted && !q.isLikelyPYQ ? ['predicted'] : [])
        ],
        qualityScore: 70,
        isPublished: false,
        review: {
          status: 'pending'
        }
      };
    });

    // Save to DB as drafts
    const saved = await Question.insertMany(
      normalized.map(q => ({ ...q, uploadedBy: req.userId }))
    );

    res.status(201).json({
      success: true,
      message: `${saved.length} questions generated by AI and saved as drafts. Review before publishing.`,
      data: saved
    });

  } catch (error) {
    console.error('❌ AI Generate Error:', error);
    const msg = error.message || 'AI generation failed';
    res.status(500).json({ success: false, message: msg });
  }
};
