// Curated by Codex from NCERT Biology concepts. Each association is independently
// grounded against the official chapter PDF by generateCodexBiologyQuestions.js.
const concept = (entity, fact, needle, topic) => ({ entity, fact, needle: needle || entity, topic });

module.exports = {
  kebo101: [
    concept('Species', 'the basic unit of classification whose members share fundamental similarities', 'species basic unit', 'Taxonomic categories'),
    concept('Genus', 'a group of related species with more characters in common than species of other genera', 'genera aggregates closely related species', 'Taxonomic categories'),
    concept('Family', 'a taxonomic category containing related genera and showing fewer similarities than genus', 'families characterised vegetative reproductive features', 'Taxonomic categories'),
    concept('Order', 'an assemblage of related families based on a few similar characters', 'order assemblage families', 'Taxonomic categories'),
    concept('Class', 'a category that includes related orders', 'class includes orders', 'Taxonomic categories'),
    concept('Phylum', 'the category used for animals that groups related classes', 'classes comprising animals assigned phylum', 'Taxonomic categories'),
    concept('Kingdom', 'the highest category discussed in the taxonomic hierarchy', 'kingdom all animals belonging various phyla', 'Taxonomic categories'),
    concept('Binomial nomenclature', 'the naming system in which a biological name has a generic name and a specific epithet', 'biological names two components', 'Nomenclature'),
    concept('Taxon', 'a unit of classification at any rank in the hierarchy', 'taxa different levels', 'Taxonomic categories'),
    concept('Taxonomic hierarchy', 'the ordered hierarchy in which each taxonomic step represents a rank or category', 'hierarchy steps rank category taxonomic', 'Taxonomic categories')
  ],
  kebo102: [
    concept('Kingdom Monera', 'the kingdom containing prokaryotic organisms such as bacteria', 'bacteria sole members kingdom monera', 'Monera'),
    concept('Archaebacteria', 'bacteria with a distinctive cell wall that enables survival in extreme habitats', 'archaebacteria special cell wall structure', 'Monera'),
    concept('Eubacteria', 'the true bacteria characterised by a rigid cell wall and, when motile, a flagellum', 'eubacteria true bacteria rigid cell wall', 'Monera'),
    concept('Cyanobacteria', 'photosynthetic autotrophs that may be unicellular, colonial or filamentous', 'cyanobacteria photosynthetic autotrophs', 'Monera'),
    concept('Mycoplasma', 'the smallest living cells that completely lack a cell wall', 'mycoplasma completely lack cell wall', 'Monera'),
    concept('Kingdom Protista', 'the kingdom containing primarily unicellular eukaryotes', 'all single celled eukaryotes protista', 'Protista'),
    concept('Diatoms', 'chief producers in oceans whose indestructible siliceous walls form diatomaceous earth', 'diatoms walls form two thin overlapping shells', 'Protista'),
    concept('Dinoflagellates', 'mostly marine photosynthetic protists with two flagella and stiff cellulose plates', 'dinoflagellates two flagella', 'Protista'),
    concept('Euglenoids', 'freshwater protists with a protein-rich pellicle instead of a cell wall', 'euglenoids pellicle instead cell wall', 'Protista'),
    concept('Slime moulds', 'saprophytic protists that form an aggregation called a plasmodium under suitable conditions', 'slime moulds plasmodium', 'Protista')
  ],
  kebo103: [
    concept('Chlorophyceae', 'green algae whose major pigments are chlorophyll a and b', 'chlorophyceae chlorophyll a and b', 'Algae'),
    concept('Phaeophyceae', 'brown algae containing chlorophyll a, c and fucoxanthin', 'brown algae fucoxanthin', 'Algae'),
    concept('Rhodophyceae', 'red algae in which r-phycoerythrin is the predominant pigment', 'rhodophyceae r phycoerythrin', 'Algae'),
    concept('Bryophytes', 'amphibians of the plant kingdom that require water for sexual reproduction', 'bryophytes amphibians plant kingdom', 'Bryophytes'),
    concept('Liverworts', 'bryophytes whose thalloid body is dorsiventral and closely appressed to the substrate', 'liverworts thalloid dorsiventral', 'Bryophytes'),
    concept('Mosses', 'bryophytes with a predominant gametophyte having protonema and leafy stages', 'moss gametophyte protonema leafy stage', 'Bryophytes'),
    concept('Pteridophytes', 'the first terrestrial plants to possess vascular tissues', 'pteridophytes first terrestrial vascular tissues', 'Pteridophytes'),
    concept('Heterospory', 'the production of distinct microspores and megaspores', 'two kinds spores microspores megaspores', 'Pteridophytes'),
    concept('Gymnosperms', 'seed plants whose ovules are not enclosed by an ovary wall', 'gymnosperms ovules not enclosed ovary wall', 'Gymnosperms'),
    concept('Angiosperms', 'flowering plants whose seeds are enclosed within fruits', 'angiosperms seeds enclosed fruits', 'Angiosperms')
  ],
  kebo104: [
    concept('Porifera', 'animals with a canal system in which water enters through ostia and leaves through the osculum', 'water transport canal system ostia osculum', 'Animal classification'),
    concept('Cnidaria', 'aquatic animals bearing stinging cnidoblasts on tentacles and body', 'cnidoblasts tentacles body', 'Animal classification'),
    concept('Ctenophora', 'marine animals with eight external rows of ciliated comb plates', 'eight external rows ciliated comb plates', 'Animal classification'),
    concept('Platyhelminthes', 'bilaterally symmetrical, triploblastic acoelomates with a dorsoventrally flattened body', 'platyhelminthes dorsoventrally flattened', 'Animal classification'),
    concept('Aschelminthes', 'roundworms with a pseudocoelom and complete digestive tract', 'aschelminthes pseudocoelom', 'Animal classification'),
    concept('Annelida', 'metamerically segmented coelomates with a closed circulatory system', 'annelida metamerically segmented', 'Animal classification'),
    concept('Arthropoda', 'the largest animal phylum, characterised by jointed appendages and a chitinous exoskeleton', 'arthropoda jointed appendages chitinous exoskeleton', 'Animal classification'),
    concept('Mollusca', 'animals with a muscular foot, visceral hump and mantle', 'mollusca muscular foot visceral hump mantle', 'Animal classification'),
    concept('Echinodermata', 'marine animals with a water vascular system and calcareous endoskeleton', 'echinoderms water vascular system', 'Animal classification'),
    concept('Chordata', 'animals possessing a notochord, dorsal hollow nerve cord and paired pharyngeal gill slits', 'chordates notochord dorsal hollow nerve cord', 'Animal classification')
  ],
  kebo105: [
    concept('Root cap', 'the structure that protects the tender root apex as it penetrates soil', 'root cap protects tender apex', 'Root'),
    concept('Tap root system', 'the root system formed by direct elongation of the radicle in most dicotyledonous plants', 'direct elongation radicle tap root system dicotyledonous', 'Root'),
    concept('Fibrous root system', 'the root system in which the primary root is replaced by many roots arising from the base of the stem', 'primary root replaced roots base stem fibrous', 'Root'),
    concept('Adventitious roots', 'roots that arise from plant parts other than the radicle, as in grass, Monstera and banyan', 'grass Monstera banyan roots other than radicle adventitious', 'Root'),
    concept('Alternate phyllotaxy', 'an arrangement with one leaf at each node in an alternate manner', 'alternate phyllotaxy single leaf each node', 'Leaf'),
    concept('Reticulate venation', 'a leaf venation pattern in which veinlets form a network', 'veinlets form network reticulate', 'Leaf'),
    concept('Racemose inflorescence', 'an inflorescence with an indefinitely growing main axis and acropetal flower succession', 'racemose main axis continues grow acropetal', 'Inflorescence'),
    concept('Cymose inflorescence', 'an inflorescence whose main axis terminates in a flower', 'cymose main axis terminates flower', 'Inflorescence'),
    concept('Axile placentation', 'placentation in which ovules are attached to a central axis in a multilocular ovary', 'axile placentation central axis', 'Flower'),
    concept('Valvate aestivation', 'an arrangement in which sepals or petals touch without overlapping', 'valvate touch one another without overlapping', 'Flower')
  ],
  kebo106: [
    concept('Bulliform cells', 'large, empty and colourless modified adaxial epidermal cells found along the veins of grass leaves', 'adaxial epidermal cells veins large empty colourless bulliform cells', 'Leaf anatomy'),
    concept('Parenchyma', 'living, thin-walled simple tissue that often performs photosynthesis or storage', 'parenchyma thin walled living cells', 'Simple tissues'),
    concept('Collenchymatous hypodermis', 'a few cell layers just below the epidermis that provide mechanical strength to a young dicot stem', 'hypodermis collenchymatous cells below epidermis mechanical strength young stem', 'Stem anatomy'),
    concept('Mesophyll', 'the leaf ground tissue made of thin-walled chloroplast-containing cells', 'leaves ground tissue thin walled chloroplast cells mesophyll', 'Ground tissue'),
    concept('Xylem', 'complex tissue that conducts water and minerals from roots to aerial parts', 'xylem conducts water minerals', 'Complex tissues'),
    concept('Phloem', 'complex tissue responsible for transport of food materials', 'phloem transports food', 'Complex tissues'),
    concept('Dicot stem', 'a stem with vascular bundles arranged in a ring and open due to cambium', 'dicot stem vascular bundles ring open', 'Stem anatomy'),
    concept('Monocot stem', 'a stem with numerous closed vascular bundles scattered in ground tissue', 'monocot stem vascular bundles scattered', 'Stem anatomy'),
    concept('Secondary growth', 'increase in girth produced by vascular cambium and cork cambium', 'secondary growth vascular cambium cork cambium', 'Secondary growth'),
    concept('Stomatal apparatus', 'the stomatal pore together with guard cells and subsidiary cells', 'stomatal apparatus guard cells subsidiary cells', 'Epidermal tissue')
  ],
  kebo107: [
    concept('Animal tissue', 'a group of similar cells with intercellular substances that performs a specific function', 'group similar cells intercellular substances specific function tissue', 'Organ and organ system'),
    concept('Organ system', 'two or more organs working together through physical or chemical interaction to perform a common function', 'two more organs common function interaction organ system', 'Organ and organ system'),
    concept('Poikilothermy in frog', 'the condition in which body temperature varies with environmental temperature', 'frog body temperature varies environment cold blooded poikilotherm', 'Frog morphology'),
    concept('Aestivation in frog', 'the summer sleep in deep burrows that protects a frog from extreme heat', 'summer sleep aestivation deep burrows extreme heat', 'Frog morphology'),
    concept('Hibernation in frog', 'the winter sleep in deep burrows that protects a frog from extreme cold', 'winter sleep hibernation deep burrows extreme cold', 'Frog morphology'),
    concept('Cutaneous respiration in frog', 'the exchange of dissolved oxygen through moist skin while the frog is in water', 'water skin aquatic respiratory organ cutaneous respiration diffusion', 'Frog respiration'),
    concept('Frog heart', 'a three-chambered muscular organ with two atria and one ventricle', 'heart three chambers two atria one ventricle frog', 'Frog circulation'),
    concept('Hepatic portal system in frog', 'the special venous connection between the liver and intestine', 'special venous connection liver intestine hepatic portal system', 'Frog circulation'),
    concept('Ureotelic frog', 'a frog excretes nitrogenous waste mainly as urea', 'frog excretes urea ureotelic animal', 'Frog excretion'),
    concept('Frog development', 'external fertilisation in water produces a tadpole that metamorphoses into the adult', 'fertilisation external water tadpole metamorphosis adult frog', 'Frog reproduction')
  ],
  kebo108: [
    concept('Prokaryotic cell', 'a cell lacking a membrane-bound nucleus and membrane-bound organelles', 'lack membrane bound nucleus prokaryotic', 'Cell types'),
    concept('Eukaryotic cell', 'a cell with a membrane-bound nucleus and compartmentalised cytoplasm', 'membrane bound nuclei eukaryotic', 'Cell types'),
    concept('Plasma membrane', 'a selectively permeable lipid bilayer described by the fluid mosaic model', 'fluid mosaic model plasma membrane', 'Cell membrane'),
    concept('Cell wall', 'a non-living rigid structure that gives shape and protection outside the plasma membrane', 'cell wall gives shape protects', 'Cell envelope'),
    concept('Endoplasmic reticulum', 'a membranous network involved in intracellular transport; rough ER bears ribosomes', 'endoplasmic reticulum network membranous', 'Endomembrane system'),
    concept('Golgi apparatus', 'stacked cisternae that modify, package and dispatch materials', 'golgi materials packaged', 'Endomembrane system'),
    concept('Lysosome', 'a single-membrane vesicle rich in hydrolytic enzymes active at acidic pH', 'lysosomes hydrolytic enzymes acidic', 'Endomembrane system'),
    concept('Mitochondrion', 'a double-membrane organelle whose inner membrane forms cristae and produces ATP', 'mitochondria cristae ATP', 'Mitochondria'),
    concept('Ribosome', 'a non-membranous ribonucleoprotein particle that is the site of protein synthesis', 'ribosomes site protein synthesis', 'Ribosomes'),
    concept('Centriole', 'a cylindrical structure with nine peripheral triplet fibrils', 'centriole nine peripheral triplet fibrils', 'Centrosome')
  ],
  kebo109: [
    concept('Primary metabolites', 'metabolites with identifiable roles in normal physiological processes', 'primary metabolites normal physiological processes', 'Metabolites'),
    concept('Secondary metabolites', 'compounds such as alkaloids and pigments whose functions are not always understood', 'secondary metabolites alkaloids pigments', 'Metabolites'),
    concept('Protein', 'a heteropolymer made from amino acid monomers', 'proteins heteropolymers amino acids', 'Proteins'),
    concept('Amino acid', 'an organic molecule containing amino and carboxyl groups attached to the same carbon', 'amino acid amino carboxyl groups', 'Proteins'),
    concept('Peptide bond', 'the bond formed between the carboxyl group of one amino acid and amino group of another', 'peptide bond carboxyl amino group', 'Proteins'),
    concept('Enzyme', 'a catalyst that lowers the activation-energy barrier and remains unchanged after catalysis', 'enzymes activation energy barrier unchanged catalysis', 'Enzymes'),
    concept('Activation energy', 'the energy barrier separating reactants from products that enzymes lower', 'activation energy enzymes', 'Enzymes'),
    concept('Nucleic acid', 'a polynucleotide made of nucleotide monomers', 'nucleic acids polynucleotides', 'Nucleic acids'),
    concept('Polysaccharide', 'a long chain of monosaccharide units linked by glycosidic bonds', 'polysaccharides long chains sugars', 'Carbohydrates'),
    concept('Lipid', 'a water-insoluble biomolecule that is not a true polymer', 'lipids not strictly macromolecules', 'Lipids')
  ],
  kebo110: [
    concept('G1 phase', 'the interval after mitosis in which a cell grows and remains metabolically active', 'G1 cell metabolically active grows', 'Cell cycle'),
    concept('S phase', 'the cell-cycle phase in which DNA replication occurs without an increase in chromosome number', 'S phase DNA replication', 'Cell cycle'),
    concept('G2 phase', 'the interval after DNA replication when proteins required for mitosis are synthesised', 'G2 proteins synthesised preparation mitosis', 'Cell cycle'),
    concept('M phase', 'the phase that includes nuclear division followed by cytoplasmic division', 'M phase karyokinesis cytokinesis', 'Cell cycle'),
    concept('Prophase', 'the mitotic stage marked by chromosome condensation and disappearance of the nucleolus', 'prophase chromosomal condensation', 'Mitosis'),
    concept('Metaphase', 'the mitotic stage when chromosomes align at the equatorial plate', 'metaphase plate chromosomes', 'Mitosis'),
    concept('Anaphase', 'the stage when centromeres split and sister chromatids move to opposite poles', 'anaphase centromeres split chromatids', 'Mitosis'),
    concept('Telophase', 'the stage when chromosomes decondense and nuclear envelopes re-form', 'telophase nuclear envelope assembles', 'Mitosis'),
    concept('Cytokinesis', 'division of the cytoplasm that follows karyokinesis', 'cytokinesis division cytoplasm', 'Cell division'),
    concept('Meiosis', 'a reduction division that produces haploid cells while generating variation', 'meiosis reduction chromosome number', 'Meiosis')
  ],
  kebo111: [
    concept('Chlorophyll a', 'the chief pigment associated with the reaction centre in photosynthesis', 'chlorophyll a chief pigment', 'Photosynthetic pigments'),
    concept('Action spectrum', 'a graph showing the effectiveness of different wavelengths in photosynthesis', 'action spectrum rate photosynthesis wavelength', 'Light absorption'),
    concept('Light reaction', 'the photochemical phase that produces ATP and NADPH in thylakoid membranes', 'light reaction ATP NADPH', 'Light reaction'),
    concept('Photolysis', 'light-driven splitting of water that supplies electrons and releases oxygen', 'splitting water oxygen electrons', 'Light reaction'),
    concept('Cyclic photophosphorylation', 'ATP formation involving PSI alone without NADPH or oxygen production', 'cyclic photophosphorylation only photosystem I', 'Photophosphorylation'),
    concept('Non-cyclic photophosphorylation', 'electron flow through both photosystems that yields ATP, NADPH and oxygen', 'non cyclic both photosystems ATP NADPH', 'Photophosphorylation'),
    concept('Chemiosmosis', 'ATP synthesis driven by a proton gradient across the thylakoid membrane', 'proton gradient thylakoid ATP synthesis', 'Chemiosmosis'),
    concept('Calvin cycle', 'the C3 pathway that fixes carbon dioxide through carboxylation, reduction and regeneration', 'Calvin cycle carboxylation reduction regeneration', 'Carbon fixation'),
    concept('C4 pathway', 'a pathway using PEP carboxylase initially and spatially separating initial fixation from the Calvin cycle', 'C4 PEP carboxylase bundle sheath', 'C4 pathway'),
    concept('Photorespiration', 'a pathway in which neither sugar nor ATP is synthesised while carbon dioxide is released', 'photorespiratory pathway neither synthesis sugars ATP carbon dioxide', 'Photorespiration')
  ],
  kebo112: [
    concept('Glycolysis', 'the cytoplasmic pathway that converts glucose into two molecules of pyruvate', 'glycolysis glucose pyruvic acid', 'Glycolysis'),
    concept('Alcoholic fermentation', 'anaerobic conversion of pyruvate to ethanol and carbon dioxide', 'pyruvic acid ethanol carbon dioxide', 'Fermentation'),
    concept('Lactic acid fermentation', 'anaerobic conversion of pyruvate into lactic acid in muscle under limited oxygen', 'lactic acid muscle oxygen inadequate', 'Fermentation'),
    concept('Acetyl CoA', 'the two-carbon compound that enters the tricarboxylic acid cycle', 'acetyl CoA enters tricarboxylic acid cycle', 'Aerobic respiration'),
    concept('Krebs cycle', 'the mitochondrial matrix pathway that completely oxidises the acetyl group', 'Krebs cycle mitochondrial matrix', 'Aerobic respiration'),
    concept('Electron transport system', 'a series of inner-membrane carriers that transfers electrons to oxygen', 'electron transport inner mitochondrial membrane oxygen', 'ETS'),
    concept('Oxidative phosphorylation', 'ATP synthesis coupled to oxidation of reduced coenzymes through the electron transport system', 'oxidative phosphorylation ATP electron transport', 'ETS'),
    concept('Respiratory quotient', 'the ratio of the volume of carbon dioxide evolved to the volume of oxygen consumed in respiration', 'ratio volume carbon dioxide evolved volume oxygen consumed respiratory quotient', 'Respiratory balance'),
    concept('Amphibolic pathway', 'a pathway serving both catabolic breakdown and anabolic synthesis', 'respiratory pathway amphibolic', 'Respiratory balance'),
    concept('Proton gradient', 'the electrochemical difference used by ATP synthase to phosphorylate ADP', 'proton gradient ATP synthase', 'ETS')
  ],
  kebo113: [
    concept('Growth', 'an irreversible permanent increase in size that commonly involves cell division and enlargement', 'growth permanent irreversible increase size', 'Plant growth'),
    concept('Differentiation', 'the process by which cells mature to perform specific functions', 'cells derived meristems differentiate mature', 'Plant growth'),
    concept('Dedifferentiation', 'the regain of divisional capacity by differentiated living cells', 'dedifferentiation regain capacity divide', 'Plant growth'),
    concept('Redifferentiation', 'the maturation of dedifferentiated cells so that they again lose divisional capacity', 'redifferentiation lose capacity divide', 'Plant growth'),
    concept('Auxin', 'a plant growth regulator associated with cell elongation and apical dominance', 'auxins apical dominance', 'Plant growth regulators'),
    concept('Gibberellin', 'a regulator that promotes stem elongation and can induce bolting', 'gibberellins bolting', 'Plant growth regulators'),
    concept('Cytokinin', 'a regulator that promotes cell division and helps overcome apical dominance', 'cytokinins cell division', 'Plant growth regulators'),
    concept('Ethylene', 'a gaseous regulator that promotes fruit ripening and senescence', 'ethylene fruit ripening', 'Plant growth regulators'),
    concept('Abscisic acid', 'a stress hormone that promotes stomatal closure and dormancy', 'abscisic acid stress hormone stomata', 'Plant growth regulators')
  ],
  kebo114: [
    concept('Inspiration', 'the phase in which diaphragm contraction increases thoracic volume and lowers intrapulmonary pressure', 'inspiration diaphragm contracts thoracic volume', 'Breathing'),
    concept('Expiration', 'the phase in which relaxation reduces thoracic volume and raises intrapulmonary pressure', 'expiration diaphragm relaxes', 'Breathing'),
    concept('Tidal volume', 'the volume of air inspired or expired during normal breathing', 'tidal volume normal respiration', 'Respiratory volumes'),
    concept('Inspiratory reserve volume', 'the additional air that can be inspired forcibly after a normal inspiration', 'inspiratory reserve volume additional air', 'Respiratory volumes'),
    concept('Expiratory reserve volume', 'the additional air that can be expired forcibly after a normal expiration', 'expiratory reserve volume additional air', 'Respiratory volumes'),
    concept('Residual volume', 'air remaining in lungs even after a forcible expiration', 'residual volume remains lungs', 'Respiratory volumes'),
    concept('Vital capacity', 'the maximum air expelled after a maximum inspiration', 'vital capacity maximum volume', 'Respiratory capacities'),
    concept('Alveoli', 'thin, vascular exchange surfaces across which oxygen and carbon dioxide diffuse', 'alveoli diffusion gases', 'Gas exchange'),
    concept('Bicarbonate', 'the principal form in which carbon dioxide is transported in blood', 'carbon dioxide transported bicarbonate', 'Gas transport')
  ],
  kebo115: [
    concept('Plasma', 'the straw-coloured fluid matrix of blood containing water, proteins and solutes', 'plasma straw coloured fluid', 'Blood'),
    concept('Erythrocytes', 'enucleated biconcave cells containing haemoglobin for oxygen transport', 'erythrocytes biconcave haemoglobin', 'Blood cells'),
    concept('Leucocytes', 'nucleated colourless blood cells involved mainly in defence', 'leucocytes colourless nucleated', 'Blood cells'),
    concept('Platelets', 'cell fragments derived from megakaryocytes that participate in coagulation', 'platelets megakaryocytes coagulation', 'Blood cells'),
    concept('ABO blood group', 'a grouping based on A and B antigens on erythrocytes and corresponding plasma antibodies', 'ABO antigens antibodies', 'Blood groups'),
    concept('Blood coagulation', 'a cascade that converts fibrinogen into a fibrin mesh', 'fibrinogen fibrin clot', 'Coagulation'),
    concept('Cardiac cycle', 'the repeating sequence of atrial systole, ventricular systole and joint diastole', 'cardiac cycle atrial ventricular systole', 'Heart'),
    concept('Electrocardiogram', 'a graphical record of the electrical activity of the heart', 'electrocardiogram electrical activity heart', 'Heart'),
    concept('Double circulation', 'circulation in which blood passes through the heart twice in one complete circuit', 'double circulation passes heart twice', 'Circulation')
  ],
  kebo116: [
    concept('Ammonotelism', 'excretion of highly toxic ammonia, requiring abundant water', 'ammonia ammonotelic', 'Nitrogenous wastes'),
    concept('Ureotelism', 'excretion of urea after conversion of ammonia, typical of mammals', 'urea ureotelic animals', 'Nitrogenous wastes'),
    concept('Uricotelism', 'excretion of relatively insoluble uric acid with minimum water loss', 'uric acid uricotelic', 'Nitrogenous wastes'),
    concept('Nephron', 'the structural and functional unit of the kidney', 'nephron functional unit kidney', 'Kidney'),
    concept('Ultrafiltration', 'pressure filtration of blood from glomerular capillaries into Bowman’s capsule', 'glomerular filtration ultrafiltration', 'Urine formation'),
    concept('Selective reabsorption', 'recovery of useful substances from tubular filtrate into blood', 'tubular reabsorption useful substances', 'Urine formation'),
    concept('Counter-current mechanism', 'the opposing flow system in Henle’s loop and vasa recta that concentrates urine', 'counter current Henle vasa recta', 'Urine concentration'),
    concept('Antidiuretic hormone', 'a hormone that increases water reabsorption in distal tubules and collecting ducts', 'ADH water reabsorption', 'Kidney regulation'),
    concept('Renin-angiotensin mechanism', 'a regulatory pathway activated by reduced glomerular blood flow to raise pressure and filtration', 'renin angiotensin glomerular blood flow', 'Kidney regulation')
  ],
  kebo117: [
    concept('Amoeboid movement', 'movement produced by pseudopodia through cytoplasmic streaming', 'amoeboid movement pseudopodia', 'Movement'),
    concept('Ciliary movement', 'movement generated by coordinated beating of cilia in structures such as trachea and oviducts', 'ciliary movement trachea oviducts', 'Movement'),
    concept('Muscular movement', 'movement caused by the contractile properties of muscle fibres', 'muscular movement contractile muscle', 'Movement'),
    concept('Sarcomere', 'the functional contractile unit between two successive Z lines', 'sarcomere two Z lines', 'Skeletal muscle'),
    concept('Sliding filament mechanism', 'contraction produced when thin filaments slide over thick filaments without changing length', 'thin filaments slide thick filaments', 'Muscle contraction'),
    concept('Calcium ions', 'ions released from sarcoplasmic reticulum that expose active sites on actin', 'calcium binds troponin active sites', 'Muscle contraction'),
    concept('Red muscle fibres', 'myoglobin-rich fibres with abundant mitochondria adapted for sustained activity', 'red fibres myoglobin mitochondria', 'Muscle types'),
    concept('Synovial joint', 'a freely movable joint with a fluid-filled cavity', 'synovial joints fluid filled cavity', 'Joints'),
    concept('Myasthenia gravis', 'an autoimmune disorder causing skeletal muscle weakness', 'myasthenia gravis autoimmune', 'Muscle disorders')
  ],
  kebo118: [
    concept('Neuron', 'the structural and functional unit of the neural system', 'neuron structural functional unit neural', 'Neural tissue'),
    concept('Axon', 'a long neuronal process that transmits impulses away from the cell body', 'axon transmits nerve impulses', 'Neuron'),
    concept('Chemical synapse', 'a junction where neurotransmitter carries a signal across a synaptic cleft', 'chemical synapse neurotransmitters', 'Synapse'),
    concept('Central neural system', 'the division consisting of brain and spinal cord', 'central neural system brain spinal cord', 'Neural system'),
    concept('Peripheral neural system', 'the division comprising nerves associated with the central neural system', 'peripheral neural system nerves', 'Neural system'),
    concept('Cerebrum', 'the major part of the human brain, divided into two hemispheres connected by the corpus callosum', 'cerebrum two cerebral hemispheres corpus callosum', 'Human brain'),
    concept('Hypothalamus', 'the diencephalic region containing centres that control body temperature and urges for eating and drinking', 'hypothalamus centres body temperature eating drinking', 'Human brain'),
    concept('Medulla oblongata', 'the brain region containing centres that control respiration, cardiovascular reflexes and gastric secretions', 'medulla centres respiration cardiovascular reflexes gastric secretions', 'Human brain'),
    concept('Resting potential', 'the membrane potential maintained by unequal ion distribution across an unstimulated neuronal membrane', 'resting membrane polarised sodium potassium', 'Nerve impulse')
  ],
  kebo119: [
    concept('Hypothalamus', 'the brain region containing neurosecretory cells that regulate pituitary function', 'hypothalamus neurosecretory cells', 'Endocrine control'),
    concept('Pituitary gland', 'the gland whose anterior lobe secretes trophic hormones controlling several endocrine glands', 'pituitary trophic hormones', 'Endocrine glands'),
    concept('Thyroid gland', 'the gland producing iodinated hormones that regulate basal metabolism', 'thyroid hormones basal metabolic rate', 'Endocrine glands'),
    concept('Parathyroid hormone', 'a hormone that raises blood calcium concentration', 'parathyroid hormone increases calcium', 'Endocrine glands'),
    concept('Adrenal medulla', 'the source of adrenaline and noradrenaline during emergency responses', 'adrenal medulla adrenaline noradrenaline', 'Endocrine glands'),
    concept('Islets of Langerhans', 'the endocrine component of the pancreas, representing about one to two per cent of pancreatic tissue', 'endocrine pancreas Islets Langerhans one two per cent pancreatic tissue', 'Endocrine pancreas'),
    concept('Testosterone', 'an androgen from Leydig cells that supports male secondary sexual characters', 'Leydig cells androgens', 'Gonadal hormones'),
    concept('Oestrogen', 'an ovarian hormone promoting female secondary sexual characters and reproductive growth', 'ovary oestrogen female secondary sexual characters', 'Gonadal hormones'),
    concept('Hormone-receptor complex', 'the complex formed when a hormone binds its specific receptor in a target tissue to regulate cellular metabolism', 'hormones bind specific receptors target tissues hormone receptor complex metabolism', 'Hormone action')
  ],
  lebo101: [
    concept('Microsporogenesis', 'formation of haploid microspores from pollen mother cells by meiosis', 'microsporogenesis pollen mother cell meiosis', 'Male gametophyte'),
    concept('Pollen grain', 'the partially developed male gametophyte of flowering plants', 'pollen grain male gametophyte', 'Male gametophyte'),
    concept('Tapetum', 'the innermost anther wall layer that nourishes developing pollen grains', 'tapetum nourishes developing pollen', 'Anther'),
    concept('Megasporogenesis', 'formation of megaspores from a megaspore mother cell by meiosis', 'megasporogenesis megaspore mother cell', 'Female gametophyte'),
    concept('Embryo sac', 'the female gametophyte that is typically seven-celled and eight-nucleate', 'embryo sac seven celled eight nucleate', 'Female gametophyte'),
    concept('Pollination', 'transfer of pollen grains from anther to stigma', 'pollination transfer pollen anther stigma', 'Pollination'),
    concept('Double fertilisation', 'the angiosperm event combining syngamy and triple fusion', 'double fertilisation syngamy triple fusion', 'Fertilisation'),
    concept('Endosperm', 'the usually triploid tissue that nourishes the developing embryo', 'endosperm triploid nourishes embryo', 'Post-fertilisation'),
    concept('Apomixis', 'seed formation without fertilisation', 'apomixis seed without fertilisation', 'Special reproduction')
  ],
  lebo102: [
    concept('Testis', 'the male gonad containing seminiferous tubules where sperm are formed', 'testis seminiferous tubules', 'Male reproductive system'),
    concept('Spermatogenesis', 'formation of spermatozoa from spermatogonia in seminiferous tubules', 'spermatogenesis spermatogonia spermatozoa', 'Gametogenesis'),
    concept('Spermatozoon', 'a motile male gamete with head, neck, middle piece and tail', 'sperm head neck middle piece tail', 'Male gamete'),
    concept('Ovary', 'the female gonad that produces ova and ovarian hormones', 'ovary produces ova hormones', 'Female reproductive system'),
    concept('Oogenesis', 'formation and maturation of the female gamete beginning before birth', 'oogenesis initiated embryonic development', 'Gametogenesis'),
    concept('Menstrual cycle', 'the approximately monthly cyclic changes in primate female reproductive organs', 'menstrual cycle primates', 'Reproductive cycle'),
    concept('Fertilisation', 'fusion of a sperm with an ovum after both reach the ampullary region of the fallopian tube', 'sperm ovum ampullary region fallopian tube fertilisation', 'Fertilisation'),
    concept('Implantation', 'attachment and embedding of the blastocyst in the uterine endometrium', 'blastocyst implantation endometrium', 'Pregnancy'),
    concept('Placenta', 'the temporary foetomaternal organ for exchange and endocrine support', 'placenta foetal maternal tissues hormones', 'Pregnancy')
  ],
  lebo103: [
    concept('Contraception', 'intentional prevention of conception or pregnancy', 'contraceptive methods prevent pregnancy', 'Birth control'),
    concept('Periodic abstinence', 'avoiding intercourse during the fertile period of the menstrual cycle', 'periodic abstinence fertile period', 'Natural methods'),
    concept('Barrier method', 'a method that physically prevents sperm from reaching the ovum', 'barriers prevent meeting sperm ovum', 'Contraception'),
    concept('Intrauterine device', 'a device inserted into the uterus that increases phagocytosis of sperms; copper-releasing types also suppress sperm motility', 'Intra Uterine Devices uterus phagocytosis sperms copper motility', 'Contraception'),
    concept('Oral contraceptive pill', 'a hormonal preparation that inhibits ovulation and implantation', 'pills inhibit ovulation implantation', 'Contraception'),
    concept('Sterilisation', 'a terminal method that blocks gamete transport through vasectomy or tubectomy', 'vasectomy tubectomy gamete transport', 'Contraception'),
    concept('Medical termination of pregnancy', 'intentional termination of pregnancy before full term under medical supervision', 'medical termination pregnancy MTP', 'MTP'),
    concept('Sexually transmitted infection', 'an infection transmitted mainly through sexual contact and reduced by early diagnosis and safe practices', 'sexually transmitted infections early detection', 'STIs'),
    concept('Assisted reproductive technology', 'clinical techniques such as IVF used to address infertility', 'assisted reproductive technologies infertility', 'Infertility')
  ],
  lebo104: [
    concept('Monohybrid cross', 'a cross that follows inheritance of one pair of contrasting traits', 'monohybrid cross one character', 'Mendelian inheritance'),
    concept('Law of dominance', 'the principle that one allele expresses in a heterozygote while the other is recessive', 'law dominance heterozygous', 'Mendelian inheritance'),
    concept('Law of segregation', 'the principle that paired alleles separate during gamete formation', 'alleles segregate gamete formation', 'Mendelian inheritance'),
    concept('Test cross', 'a cross between an individual of unknown dominant genotype and a recessive parent', 'test cross recessive parent', 'Mendelian inheritance'),
    concept('Dihybrid cross', 'a cross following two pairs of contrasting characters', 'dihybrid cross two traits', 'Mendelian inheritance'),
    concept('Independent assortment', 'independent segregation of alleles of different genes when the genes are unlinked', 'independent assortment two pairs factors', 'Mendelian inheritance'),
    concept('Incomplete dominance', 'inheritance in which the heterozygote has an intermediate phenotype', 'incomplete dominance intermediate phenotype', 'Non-Mendelian inheritance'),
    concept('Codominance', 'inheritance in which both alleles express in a heterozygote', 'codominance both alleles express', 'Non-Mendelian inheritance'),
    concept('Linkage', 'the tendency of genes on the same chromosome to be inherited together', 'genes same chromosome linkage', 'Chromosomal inheritance')
  ],
  lebo105: [
    concept('DNA', 'the genetic material in most organisms, built as an antiparallel double helix', 'DNA double helix antiparallel', 'DNA'),
    concept('Nucleosome', 'DNA wrapped around a histone octamer, forming the basic chromatin unit', 'nucleosome histone octamer', 'DNA packaging'),
    concept('Semiconservative replication', 'replication in which each daughter DNA retains one parental strand', 'semiconservative replication parental strand', 'Replication'),
    concept('Transcription', 'synthesis of RNA using a DNA template', 'transcription RNA DNA template', 'Gene expression'),
    concept('Genetic code', 'the triplet code that is degenerate, nearly universal and read without punctuation', 'genetic code triplet degenerate universal', 'Genetic code'),
    concept('Translation', 'polymerisation of amino acids into a polypeptide according to mRNA codons', 'translation amino acids polypeptide mRNA', 'Gene expression'),
    concept('Lac operon', 'an inducible bacterial operon regulated by lactose availability', 'lac operon inducible lactose', 'Gene regulation'),
    concept('Human Genome Project', 'an international programme to sequence the human genome and identify genes', 'human genome project sequence identify genes', 'Genome'),
    concept('DNA fingerprinting', 'identification based on polymorphism in repetitive DNA sequences', 'DNA fingerprinting repetitive DNA polymorphism', 'DNA fingerprinting')
  ],
  lebo106: [
    concept('Chemical evolution', 'formation of complex organic molecules from simpler inorganic substances before life arose', 'chemical evolution origin life', 'Origin of life'),
    concept('Miller experiment', 'an electric-discharge experiment in methane, hydrogen, ammonia and water vapour that produced amino acids', 'Miller electric discharge methane hydrogen ammonia water vapour amino acids', 'Origin of life'),
    concept('Homologous organs', 'structures sharing basic anatomy and origin but performing different functions', 'homologous same structure different functions', 'Evolution evidence'),
    concept('Analogous organs', 'structures with different origin but similar function', 'analogous different structure same function', 'Evolution evidence'),
    concept('Adaptive radiation', 'diversification of related species from a common ancestor in a geographical area', 'adaptive radiation common ancestor geographical area', 'Evolution patterns'),
    concept('Natural selection', 'differential reproductive success of heritable variants in a population', 'natural selection reproductive fitness', 'Evolution mechanism'),
    concept('Hardy-Weinberg equilibrium', 'constant allele frequencies in an ideal population without evolutionary forces', 'Hardy Weinberg allele frequencies constant', 'Population genetics'),
    concept('Genetic drift', 'random change in allele frequency that is especially important in small populations', 'genetic drift small population', 'Evolution mechanism'),
    concept('Evolution of modern humans', 'the evolution of modern humans appears to parallel the evolution of the human brain and language', 'evolution modern man parallel human brain language', 'Human evolution')
  ],
  lebo107: [
    concept('Innate immunity', 'non-specific defence present from birth and mediated by physical, physiological, cellular and cytokine barriers', 'innate immunity non specific barriers', 'Immunity'),
    concept('Acquired immunity', 'pathogen-specific defence characterised by memory', 'acquired immunity pathogen specific memory', 'Immunity'),
    concept('Antibody', 'an immunoglobulin produced by B lymphocytes in response to an antigen', 'antibodies immunoglobulins B lymphocytes', 'Immunity'),
    concept('Vaccination', 'exposure to antigenic material that generates protective immune memory', 'vaccination memory immune response', 'Immunity'),
    concept('Allergy', 'an exaggerated immune response to environmental antigens involving IgE', 'allergy IgE antibodies', 'Immune disorders'),
    concept('AIDS', 'an immunodeficiency caused by HIV destruction of helper T lymphocytes', 'HIV helper T lymphocytes', 'AIDS'),
    concept('Cancer', 'uncontrolled cell proliferation that may invade tissues and metastasise', 'cancer uncontrolled cell division metastasis', 'Cancer'),
    concept('Addiction', 'a psychological attachment to effects such as euphoria and a temporary feeling of well-being associated with drugs or alcohol', 'addiction psychological attachment euphoria temporary feeling well being drugs alcohol', 'Drug abuse'),
    concept('Malaria', 'a Plasmodium infection transmitted by female Anopheles mosquitoes', 'malaria female Anopheles Plasmodium', 'Infectious disease')
  ],
  lebo108: [
    concept('Lactic acid bacteria', 'microbes that convert milk to curd and improve nutritional quality', 'lactic acid bacteria curd', 'Household products'),
    concept('Methanogens', 'anaerobic microbes that produce methane and occur in rumen and biogas digesters', 'methanogens methane biogas', 'Biogas'),
    concept('Primary sewage treatment', 'physical removal of floating and suspended solids by filtration and sedimentation', 'primary treatment filtration sedimentation', 'Sewage treatment'),
    concept('Flocs', 'masses of bacteria associated with fungal filaments in aeration tanks', 'flocs bacteria fungal filaments', 'Sewage treatment'),
    concept('Activated sludge', 'microbe-rich sediment from secondary treatment, partly recycled as inoculum', 'activated sludge inoculum aeration tank', 'Sewage treatment'),
    concept('Biogas', 'a methane-rich fuel produced by anaerobic digestion of organic waste', 'biogas methane anaerobic', 'Biogas'),
    concept('Biocontrol', 'use of living organisms to control pests and pathogens', 'biological control pests diseases', 'Biocontrol'),
    concept('Biofertiliser', 'a microbial inoculant that enriches soil nutrient quality', 'biofertilisers enrich nutrient quality soil', 'Biofertilisers'),
    concept('Antibiotic', 'a chemical substance produced by some microbes that kills or retards the growth of disease-causing microbes', 'antibiotics chemical substances produced microbes kill retard growth disease causing', 'Industrial products')
  ],
  lebo109: [
    concept('Restriction endonuclease', 'an enzyme that cuts DNA at specific recognition sequences', 'restriction endonuclease recognition sequence', 'Recombinant DNA'),
    concept('DNA ligase', 'an enzyme that joins DNA fragments by forming phosphodiester bonds', 'DNA ligase joins fragments', 'Recombinant DNA'),
    concept('Cloning vector', 'a DNA molecule used to carry foreign DNA into a host cell', 'cloning vector foreign DNA host', 'Vectors'),
    concept('Origin of replication', 'the vector sequence where replication begins and copy number is controlled', 'origin replication copy number', 'Vectors'),
    concept('Selectable marker', 'a vector gene that helps identify and eliminate non-transformants', 'selectable marker identify transformants', 'Vectors'),
    concept('Polymerase chain reaction', 'an in-vitro method for exponential amplification of a chosen DNA segment', 'PCR amplification DNA', 'PCR'),
    concept('Gel electrophoresis', 'separation of DNA fragments according to size through a gel under an electric field', 'gel electrophoresis separates DNA fragments', 'DNA separation'),
    concept('Competent cell', 'a host cell treated to take up recombinant DNA efficiently', 'competent cells take up DNA', 'Transformation'),
    concept('Bioreactor', 'a vessel that provides optimum growth conditions while cells biologically convert raw materials into specific products', 'bioreactors vessels raw materials biologically converted products optimum growth conditions', 'Bioprocessing')
  ],
  lebo110: [
    concept('Recombinant insulin', 'human insulin produced by expressing separate A and B chains in bacteria and joining them', 'insulin chains A B bacteria', 'Medical biotechnology'),
    concept('Gene therapy', 'correction of a genetic defect by introducing a functional gene', 'gene therapy functional gene', 'Medical biotechnology'),
    concept('Bt crop', 'a transgenic crop expressing an insecticidal protein derived from Bacillus thuringiensis', 'Bt toxin Bacillus thuringiensis crop', 'Agricultural biotechnology'),
    concept('RNA interference', 'sequence-specific silencing of mRNA by complementary double-stranded RNA', 'RNA interference silencing mRNA', 'Agricultural biotechnology'),
    concept('Transgenic animal', 'an animal carrying a foreign gene introduced and expressed experimentally', 'transgenic animals foreign gene', 'Transgenic animals'),
    concept('GEAC', 'the Indian body that evaluates the validity and safety of genetic modification applications', 'GEAC genetic modification safety', 'Biosafety'),
    concept('Biopiracy', 'unauthorised commercial use of biological resources or traditional knowledge', 'biopiracy biological resources traditional knowledge', 'Ethics'),
    concept('Biological-resource patent controversy', 'the granting of patents for products or technologies using biological resources long used by indigenous communities', 'patents products technologies biological resources indigenous people', 'Ethics'),
    concept('Molecular diagnosis', 'early disease detection using methods such as PCR, probes or ELISA', 'molecular diagnosis PCR ELISA', 'Medical biotechnology')
  ],
  lebo111: [
    concept('Ecology', 'the study of interactions among organisms and between organisms and their physical abiotic environment', 'Ecology interactions organisms physical abiotic environment', 'Organism and environment'),
    concept('Population', 'individuals of a species in a defined geographical area that share or compete for resources and can potentially interbreed', 'species well defined geographical area resources potentially interbreed population', 'Population attributes'),
    concept('Population density', 'population size expressed per unit area or volume, sometimes measured indirectly', 'population density unit area volume', 'Population attributes'),
    concept('Exponential growth', 'population growth under unlimited resources producing a J-shaped curve', 'exponential growth unlimited resources J shaped', 'Population growth'),
    concept('Logistic growth', 'population growth limited by carrying capacity and producing a sigmoid curve', 'logistic growth carrying capacity sigmoid', 'Population growth'),
    concept('Competition', 'an interaction in which both participating species are harmed while seeking a limited resource', 'competition both species harmed', 'Population interactions'),
    concept('Predation', 'an interaction in which one species kills and consumes another', 'predation predator prey', 'Population interactions'),
    concept('Parasitism', 'an interaction benefiting the parasite while harming the host', 'parasitism parasite benefits host harmed', 'Population interactions'),
    concept('Mutualism', 'an interaction in which both species benefit', 'mutualism both species benefit', 'Population interactions')
  ],
  lebo112: [
    concept('Primary productivity', 'the rate of biomass production by producers through photosynthesis', 'primary productivity biomass producers', 'Productivity'),
    concept('Decomposition', 'breakdown of detritus through fragmentation, leaching, catabolism, humification and mineralisation', 'decomposition fragmentation leaching catabolism', 'Decomposition'),
    concept('Grazing food chain', 'a food chain beginning with living green plants', 'grazing food chain producers', 'Energy flow'),
    concept('Detritus food chain', 'a food chain beginning with dead organic matter', 'detritus food chain dead organic matter', 'Energy flow'),
    concept('Food web', 'a network formed by interconnected food chains', 'food web interconnected food chains', 'Energy flow'),
    concept('Ecological pyramid', 'a graphical representation of trophic structure by number, biomass or energy', 'ecological pyramid number biomass energy', 'Ecological pyramids'),
    concept('Ten percent law', 'the approximate transfer of only one tenth of energy to the next trophic level', 'ten percent energy next trophic level', 'Energy flow'),
    concept('Standing crop', 'the mass of living material present at a trophic level at a particular time', 'trophic level mass living material particular time standing crop', 'Energy flow'),
    concept('Net primary productivity', 'gross primary productivity minus respiratory losses, leaving biomass available to heterotrophs', 'gross primary productivity respiration losses net primary productivity biomass heterotrophs', 'Productivity')
  ],
  lebo113: [
    concept('Genetic diversity', 'variation in genes within a species across its range', 'genetic diversity species', 'Levels of biodiversity'),
    concept('Species diversity', 'variation measured by the number and relative abundance of species in a region', 'species diversity variety species', 'Levels of biodiversity'),
    concept('Ecological diversity', 'variation in ecosystems, habitats and ecological processes', 'ecological diversity ecosystems', 'Levels of biodiversity'),
    concept('Latitudinal gradient', 'the pattern of greater species richness in the tropics than near the poles', 'species diversity decreases equator poles', 'Biodiversity patterns'),
    concept('Species-area relationship', 'the increase in species richness with sampled area, described by a rectangular hyperbola on arithmetic scales', 'species area relationship rectangular hyperbola', 'Biodiversity patterns'),
    concept('Co-extinction', 'loss of one species following extinction of another with which it is obligatorily associated', 'co extinction associated species', 'Biodiversity loss'),
    concept('Biodiversity hotspot', 'a region with exceptional endemism and severe habitat loss', 'hotspots high endemism habitat loss', 'Conservation priorities'),
    concept('In situ conservation', 'protection of species in their natural habitats and ecosystems', 'in situ conservation natural habitat', 'Conservation'),
    concept('Ex situ conservation', 'protection outside natural habitat in facilities such as zoos, botanical gardens or cryobanks', 'ex situ conservation outside natural habitat', 'Conservation')
  ]
};
